"""
PYTHIA translator for prismpy.

This module translates unified data to PYTHIA model input format:
- JSON configuration file with PYTHIA-specific syntax
- DSSAT .WTH weather files per site
- Site shapefile with point locations
- GeoTIFF raster files for management and soil data
- SNX DSSAT experiment template

PYTHIA Quirks (from analysis):
1. YRDOY date format: 2015001 = Jan 1, 2015
2. JSON function syntax: lookup_wth::MLCP::vector::...
3. Point shapefile: Requires ID, Latitude, Longitude fields
4. eGHR soil profiles referenced via lookup_ghr::raster::

Reference: PYTHIA/07-JSON-CONFIG-ASSEMBLY/assemble_config.py
Reference: PYTHIA/utils/wth_utils.py
"""

import json
import logging
import time
from datetime import date, datetime
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

import numpy as np
import pandas as pd

from prismpy.config.schema import (
    Platform,
    PhenologyConfig,
    PhysiologyConfig,
    ManagementConfig,
    GenericSoilConfig,
)
from prismpy.models.climate import ClimateTimeSeries, ClimateRecord
from prismpy.models.crop import CropParameters, CropCalendar
from prismpy.models.region import Region
from prismpy.models.soil import SoilProfile
from prismpy.models.spatial import SpatialGrid
from prismpy.provenance.tracker import DecisionType, ProvenanceTracker
from prismpy.translators.base import (
    BaseTranslator,
    PythiaTranslatorBase,
    TranslationResult,
    UnifiedData,
)
from prismpy.utils.date_utils import date_to_yrdoy, doy_to_date


logger = logging.getLogger(__name__)


class PythiaTranslator(PythiaTranslatorBase):
    """Translator for PYTHIA spatial DSSAT system.

    PYTHIA (Python Thinkpiece for Intelligent Agriculture) runs DSSAT
    simulations across spatial grids using weather files and soil rasters.

    Generates:
    1. shapes/sites.shp - Site point shapefile
    2. weather/*.WTH - DSSAT weather files per site
    3. raster/*.tif - Management rasters (fertilizer, planting, cultivar)
    4. templates/*.SNX - DSSAT experiment template
    5. config/pythia_config.json - Main PYTHIA JSON configuration

    Output structure:
        output_dir/
        ├── shapes/
        │   └── sites.shp (+ .shx, .dbf, .prj)
        ├── weather/
        │   └── *.WTH
        ├── raster/
        │   └── *.tif
        ├── templates/
        │   └── template.SNX
        └── config/
            └── pythia_config.json
    """

    # DSSAT weather file format constants
    WTH_HEADER = "$WEATHER DATA: Generated by prismpy"
    WTH_COLUMNS = ["DATE", "SRAD", "TMAX", "TMIN", "RAIN", "TDEW", "RHUM", "WIND"]

    def translate(self, data: UnifiedData) -> TranslationResult:
        """Translate unified data to PYTHIA format.

        Generates a complete PYTHIA package including:
        1. Site shapefile with grid points
        2. Weather files (.WTH) - downloaded from NASA POWER if not provided
        3. Soil raster - clipped from eGHR global raster
        4. Crop mask raster - clipped from SPAM 2020
        5. Management rasters (fertilizer, planting DOY, cultivar)
        6. SNX experiment template with Jinja2 variables
        7. PYTHIA JSON configuration
        8. Package metadata (manifest, provenance, README)

        Args:
            data: UnifiedData container with region, grid, climate, soil, calendar

        Returns:
            TranslationResult with output files and status
        """
        self.log_translation_start(data)
        errors = []
        warnings = []
        output_files = []

        # Validate input data
        input_errors = self.validate_input_data(data)
        if input_errors:
            return self.create_result(
                success=False,
                output_files=[],
                errors=input_errors,
            )

        # Create output subdirectories
        for subdir in self.OUTPUT_SUBDIRS:
            (self.output_dir / subdir).mkdir(parents=True, exist_ok=True)

        try:
            # 1. Generate site shapefile
            if data.grid:
                logger.info("Step 1/8: Generating sites shapefile...")
                shape_file = self._generate_sites_shapefile(data.grid, data.region)
                output_files.append(shape_file)

            # 2. Generate weather files (.WTH)
            # Download from NASA POWER if not enough data for all sites
            logger.info("Step 2/8: Generating weather files...")
            climate_data = data.climate
            n_sites = len(data.grid.cells) if data.grid else 0

            # Check if we have enough climate data for all sites
            n_climate = len(climate_data) if climate_data else 0
            if n_climate < n_sites and data.grid:
                logger.info(f"Insufficient climate data ({n_climate}/{n_sites} sites), "
                           f"downloading from NASA POWER...")
                climate_data = self._download_site_weather(data)

            if climate_data:
                weather_files = self._generate_weather_files(climate_data)
                output_files.extend(weather_files)
            else:
                warnings.append("No climate data available - weather files not generated")

            # 3. Generate soil raster (clip from eGHR)
            logger.info("Step 3/8: Generating soil raster...")
            soil_raster = self._generate_soil_raster(data)
            if soil_raster:
                output_files.append(soil_raster)
            else:
                warnings.append("Soil raster not generated (eGHR not configured)")

            # 4. Generate crop mask raster (clip from SPAM)
            logger.info("Step 4/8: Generating crop mask raster...")
            crop_mask = self._generate_crop_mask_raster(data)
            if crop_mask:
                output_files.append(crop_mask)
            else:
                warnings.append("Crop mask not generated (SPAM not configured)")

            # 5. Generate management rasters
            logger.info("Step 5/8: Generating management rasters...")
            if data.crop_calendar or data.grid:
                raster_files = self._generate_management_rasters(
                    data.crop_calendar or {}, data.grid
                )
                output_files.extend(raster_files)

            # 6. Generate SNX template
            logger.info("Step 6/9: Generating SNX template...")
            snx_file = self._generate_snx_template(data)
            output_files.append(snx_file)

            # 7. Include eGHR data in package (for self-contained package)
            logger.info("Step 7/9: Including eGHR soil data in package...")
            eghr_dir = self._include_eghr_data()
            if eghr_dir:
                # Count files in eGHR directory
                eghr_files = list(eghr_dir.glob("*"))
                logger.info(f"Included {len(eghr_files)} eGHR files in package")

            # 8. Generate PYTHIA JSON configuration
            logger.info("Step 8/9: Generating PYTHIA JSON config...")
            config_file = self._generate_pythia_json(data)
            output_files.append(config_file)

            # 9. Generate package files (manifest, provenance, README)
            logger.info("Step 9/9: Generating package metadata...")
            package_files = self._generate_package_files(data)
            output_files.extend(package_files)

            # Validate outputs
            validation_errors = self.validate_outputs()
            if validation_errors:
                warnings.extend(validation_errors)

        except Exception as e:
            logger.error(f"PYTHIA translation failed: {e}")
            import traceback
            traceback.print_exc()
            errors.append(str(e))
            return self.create_result(
                success=False,
                output_files=output_files,
                errors=errors,
            )

        # Record provenance
        if self.provenance:
            self.provenance.record_decision(
                decision_type=DecisionType.FORMAT_CHOICE,
                description=f"Generated PYTHIA inputs for {data.region.name}",
                rationale="PYTHIA requires JSON config with DSSAT .WTH weather files",
                alternatives=["manual configuration"],
                reference=f"Output: {self.output_dir}",
            )

        # Count output files by type
        weather_count = len([f for f in output_files if str(f).endswith('.WTH')])
        raster_count = len([f for f in output_files if str(f).endswith('.tif')])

        result = self.create_result(
            success=True,
            output_files=output_files,
            warnings=warnings,
            metadata={
                "region": data.region.name,
                "n_sites": len(data.grid.cells) if data.grid else 0,
                "n_weather_files": weather_count,
                "n_rasters": raster_count,
                "total_files": len(output_files),
            },
        )

        self.log_translation_complete(result)
        logger.info(f"PYTHIA package complete: {len(output_files)} files generated")
        return result

    def validate_outputs(self) -> List[str]:
        """Validate generated PYTHIA outputs.

        Returns:
            List of validation error messages
        """
        errors = []

        # Check JSON config exists
        config_path = self.output_dir / "config" / "pythia_config.json"
        if not config_path.exists():
            errors.append(f"Missing pythia_config.json at {config_path}")
        else:
            # Validate JSON structure
            try:
                with open(config_path, 'r') as f:
                    config = json.load(f)

                required_keys = ["name", "default_setup", "runs"]
                for key in required_keys:
                    if key not in config:
                        errors.append(f"Missing required key '{key}' in pythia_config.json")

            except json.JSONDecodeError as e:
                errors.append(f"Invalid JSON in pythia_config.json: {e}")

        # Check weather directory
        weather_dir = self.output_dir / "weather"
        if weather_dir.exists():
            wth_files = list(weather_dir.glob("*.WTH"))
            if not wth_files:
                errors.append("No .WTH files generated in weather/")

        # Check shapes directory
        shapes_dir = self.output_dir / "shapes"
        if shapes_dir.exists():
            shp_files = list(shapes_dir.glob("*.shp"))
            if not shp_files:
                errors.append("No shapefile generated in shapes/")

        return errors

    def _generate_sites_shapefile(
        self,
        grid: SpatialGrid,
        region: Region,
    ) -> Path:
        """Generate PYTHIA sites point shapefile.

        PYTHIA requires a shapefile with:
        - ID field (unique site identifier)
        - Latitude field
        - Longitude field

        Args:
            grid: SpatialGrid with cells/sites
            region: Region for metadata

        Returns:
            Path to generated shapefile
        """
        try:
            import geopandas as gpd
            from shapely.geometry import Point

            # Create point features with SEQUENTIAL IDs (1, 2, 3, ...)
            # CRITICAL: ID must match weather file naming (1.WTH, 2.WTH, ...)
            # The lookup_wth function uses: lookup_wth::<prefix>::vector::<shapefile>::ID
            # PYTHIA looks up the ID value and constructs the weather filename from it
            features = []
            for seq_id, cell in enumerate(grid.cells, start=1):
                features.append({
                    "geometry": Point(cell.lon, cell.lat),
                    "ID": seq_id,  # Sequential ID matching weather file names
                    "CellID": cell.cell_id,  # Original grid cell ID for reference
                    "Latitude": cell.lat,
                    "Longitude": cell.lon,
                    "Region": region.name,
                })

            # Create GeoDataFrame
            gdf = gpd.GeoDataFrame(features, crs="EPSG:4326")

            # Save shapefile
            shp_path = self.output_dir / "shapes" / "sites.shp"
            gdf.to_file(shp_path)

            logger.info(f"Generated PYTHIA sites shapefile: {shp_path} ({len(features)} sites)")
            return shp_path

        except ImportError:
            logger.warning("geopandas not available, creating CSV instead")
            return self._generate_sites_csv(grid, region)

    def _generate_sites_csv(
        self,
        grid: SpatialGrid,
        region: Region,
    ) -> Path:
        """Fallback: Generate sites as CSV when geopandas unavailable.

        Args:
            grid: SpatialGrid with cells/sites
            region: Region for metadata

        Returns:
            Path to generated CSV
        """
        csv_path = self.output_dir / "shapes" / "sites.csv"

        with open(csv_path, 'w') as f:
            # Use sequential IDs to match weather file naming (1.WTH, 2.WTH, ...)
            f.write("ID,CellID,Latitude,Longitude,Region\n")
            for seq_id, cell in enumerate(grid.cells, start=1):
                f.write(f"{seq_id},{cell.cell_id},{cell.lat},{cell.lon},{region.name}\n")

        logger.info(f"Generated PYTHIA sites CSV: {csv_path}")
        return csv_path

    def _generate_weather_files(
        self,
        climate_data: Dict[int, ClimateTimeSeries],
    ) -> List[Path]:
        """Generate DSSAT .WTH weather files.

        .WTH format:
        $WEATHER DATA: ...
        @ INSI       LAT      LONG    ELEV   TAV   AMP REFHT WNDHT
          XXXX  latitude  longitude  elev   tav   amp   2.0   2.0

        @  DATE  SRAD  TMAX  TMIN  RAIN  TDEW  RHUM  WIND
        YRDOY  srad  tmax  tmin  rain  tdew  rhum  wind

        Args:
            climate_data: Dictionary of site_id to ClimateTimeSeries

        Returns:
            List of generated .WTH file paths
        """
        output_files = []
        weather_dir = self.output_dir / "weather"

        # Create a mapping of site_id to sequential number for unique file names
        site_ids = sorted(climate_data.keys())
        site_to_seq = {sid: i + 1 for i, sid in enumerate(site_ids)}

        for site_id, ts in climate_data.items():
            # Use sequential number for unique file naming (1.WTH, 2.WTH, etc.)
            seq_num = site_to_seq[site_id]
            station_code = f"{seq_num}"  # Use just the number

            # Calculate TAV (annual average temp) and AMP (amplitude)
            tav, amp = self._calculate_tav_amp(ts)

            # Determine elevation
            elev = ts.elevation if hasattr(ts, 'elevation') and ts.elevation else -99

            # Generate .WTH filename (matching legacy format: 1.WTH, 2.WTH, etc.)
            wth_path = weather_dir / f"{seq_num}.WTH"

            with open(wth_path, 'w') as f:
                # Header
                f.write(f"{self.WTH_HEADER}\n\n")

                # Station info line (4-character station code: Sxxx format)
                insi = f"S{seq_num:03d}"[:4]  # S001, S002, etc.
                f.write("@ INSI       LAT      LONG    ELEV   TAV   AMP REFHT WNDHT\n")
                f.write(f"  {insi:4s} {ts.lat:9.5f} {ts.lon:9.5f} ")
                f.write(f"{elev:7.2f} {tav:5.1f} {amp:5.1f}   2.0   2.0\n\n")

                # Data header
                f.write("@  DATE  SRAD  TMAX  TMIN  RAIN  TDEW  RHUM  WIND\n")

                # Data rows
                for record in ts.records:
                    yrdoy = date_to_yrdoy(record.date)

                    srad = record.srad if record.srad is not None else -99.0
                    tmax = record.tmax if record.tmax is not None else -99.0
                    tmin = record.tmin if record.tmin is not None else -99.0
                    rain = record.precip if record.precip is not None else 0.0
                    tdew = record.tdew if record.tdew is not None else -99.0
                    rhum = record.rh if record.rh is not None else -99.0
                    wind = record.wind if record.wind is not None else -99.0

                    # Handle missing values
                    rain = max(0, rain) if rain != -99 else 0.0

                    f.write(f"{yrdoy:7d} {srad:5.1f} {tmax:5.1f} {tmin:5.1f} ")
                    f.write(f"{rain:5.1f} {tdew:5.1f} {rhum:5.1f} {wind:5.1f}\n")

            output_files.append(wth_path)
            logger.debug(f"Generated weather file: {wth_path}")

        logger.info(f"Generated {len(output_files)} PYTHIA .WTH files")
        return output_files

    def _calculate_tav_amp(self, ts: ClimateTimeSeries) -> Tuple[float, float]:
        """Calculate TAV (annual average temperature) and AMP (amplitude).

        TAV = average of all mean temperatures
        AMP = (max monthly average - min monthly average) / 2

        Args:
            ts: ClimateTimeSeries

        Returns:
            Tuple of (TAV, AMP)
        """
        if not ts.records:
            return -99.0, -99.0

        # Calculate mean temperatures
        tmeans = []
        for record in ts.records:
            if record.tmean is not None:
                tmeans.append(record.tmean)
            elif record.tmax is not None and record.tmin is not None:
                tmeans.append((record.tmax + record.tmin) / 2)

        if not tmeans:
            return -99.0, -99.0

        tav = float(np.mean(tmeans))

        # Calculate monthly averages for AMP
        monthly_temps = {}
        for record in ts.records:
            month = record.date.month
            tmean = record.tmean if record.tmean else (record.tmax + record.tmin) / 2
            if month not in monthly_temps:
                monthly_temps[month] = []
            monthly_temps[month].append(tmean)

        if len(monthly_temps) < 2:
            amp = 5.0  # Default
        else:
            monthly_avgs = [np.mean(temps) for temps in monthly_temps.values()]
            amp = (max(monthly_avgs) - min(monthly_avgs)) / 2

        return round(tav, 1), round(amp, 1)

    def _generate_management_rasters(
        self,
        crop_calendar: Dict[int, CropCalendar],
        grid: Optional[SpatialGrid] = None,
    ) -> List[Path]:
        """Generate management GeoTIFF rasters for PYTHIA.

        Creates rasters for:
        - Planting DOY (planting_doy.tif)
        - Fertilizer application (fertilizer.tif)
        - Cultivar zone (cultivar.tif)

        Args:
            crop_calendar: Crop calendar per cell
            grid: SpatialGrid for spatial reference

        Returns:
            List of generated raster file paths
        """
        output_files = []
        raster_dir = self.output_dir / "raster"
        raster_dir.mkdir(parents=True, exist_ok=True)

        # Check if we have grid info for proper raster generation
        if grid is None or not grid.cells:
            logger.warning("No grid data available, generating minimal rasters")
            # Fall back to CSV if no grid
            return self._generate_management_csv_fallback(crop_calendar, raster_dir)

        try:
            import rasterio
            from rasterio.transform import from_bounds

            # Calculate bounds from grid cells
            lats = [cell.lat for cell in grid.cells]
            lons = [cell.lon for cell in grid.cells]
            minx, maxx = min(lons), max(lons)
            miny, maxy = min(lats), max(lats)

            # Add buffer
            buffer = 0.1
            minx -= buffer
            miny -= buffer
            maxx += buffer
            maxy += buffer

            # Calculate raster dimensions based on grid resolution
            pythia_config = None
            if self.config.platform_config and hasattr(self.config.platform_config, 'pythia'):
                pythia_config = self.config.platform_config.pythia

            resolution = pythia_config.grid_resolution if pythia_config else 0.0833
            width = max(1, int((maxx - minx) / resolution))
            height = max(1, int((maxy - miny) / resolution))

            # Create transform
            transform = from_bounds(minx, miny, maxx, maxy, width, height)

            # Get values from generic config mapping
            fertilizer_params = self._map_generic_to_fertilizer()
            cultivar_params = self._map_generic_to_cultivar()

            # Get planting DOY from config - REQUIRED
            if not self.config.crop.calendar or not self.config.crop.calendar.planting_doy:
                raise ValueError(
                    "crop.calendar.planting_doy is required for management raster generation. "
                    "Please specify the planting day of year in your config file."
                )
            planting_doy = self.config.crop.calendar.planting_doy

            # Raster metadata
            meta = {
                'driver': 'GTiff',
                'height': height,
                'width': width,
                'count': 1,
                'dtype': 'float32',
                'crs': 'EPSG:4326',
                'transform': transform,
                'nodata': -9999,
            }

            # 1. Fertilizer raster (uniform value)
            fert_value = fertilizer_params.get("fen_tot", 60)
            fert_data = np.full((height, width), fert_value, dtype=np.float32)
            fert_path = raster_dir / "fertilizer.tif"

            with rasterio.open(fert_path, 'w', **meta) as dst:
                dst.write(fert_data, 1)
                dst.update_tags(units="kg_N_per_ha", description="Fertilizer N application")

            output_files.append(fert_path)
            logger.info(f"Generated fertilizer raster: {fert_path} ({fert_value} kg N/ha)")

            # 2. Planting DOY raster (uniform value)
            plant_data = np.full((height, width), planting_doy, dtype=np.float32)
            plant_path = raster_dir / "planting_doy.tif"

            with rasterio.open(plant_path, 'w', **meta) as dst:
                dst.write(plant_data, 1)
                dst.update_tags(units="day_of_year", description="Planting day of year")

            output_files.append(plant_path)
            logger.info(f"Generated planting DOY raster: {plant_path} (DOY {planting_doy})")

            # 3. Cultivar zone raster (uniform value = zone 1)
            cultivar_zone = 1  # Single cultivar zone
            cult_data = np.full((height, width), cultivar_zone, dtype=np.float32)
            cult_path = raster_dir / "cultivar.tif"

            with rasterio.open(cult_path, 'w', **meta) as dst:
                dst.write(cult_data, 1)
                dst.update_tags(
                    units="zone_id",
                    description="Cultivar zone",
                    cultivar_code=cultivar_params.get("ingeno", "990002"),
                    cultivar_name=cultivar_params.get("cname", "MEDIUM_SEASON"),
                )

            output_files.append(cult_path)
            logger.info(f"Generated cultivar raster: {cult_path} (zone {cultivar_zone})")

            logger.info(f"Generated {len(output_files)} PYTHIA management GeoTIFFs")
            return output_files

        except ImportError:
            logger.warning("Rasterio not available, falling back to CSV")
            return self._generate_management_csv_fallback(crop_calendar, raster_dir)

    def _generate_management_csv_fallback(
        self,
        crop_calendar: Dict[int, CropCalendar],
        raster_dir: Path,
    ) -> List[Path]:
        """Fallback: Generate management data as CSV when rasterio unavailable."""
        output_files = []

        # Planting data
        planting_path = raster_dir / "planting_doy.csv"
        with open(planting_path, 'w') as f:
            f.write("CellID,PlantingDOY,HarvestDOY\n")
            for cell_id, calendar in crop_calendar.items():
                f.write(f"{cell_id},{calendar.planting_doy},{calendar.harvest_doy}\n")
        output_files.append(planting_path)

        # Fertilizer data
        fert_path = raster_dir / "fertilizer.csv"
        with open(fert_path, 'w') as f:
            f.write("CellID,FertilizerN\n")
            for cell_id, calendar in crop_calendar.items():
                fert_n = getattr(calendar, 'fertilizer_n', 0)
                f.write(f"{cell_id},{fert_n}\n")
        output_files.append(fert_path)

        logger.info(f"Generated {len(output_files)} PYTHIA management CSVs (fallback)")
        return output_files

    def _get_dssat_executable(self) -> str:
        """Get DSSAT executable path from config.

        IMPORTANT: Default to Windows path since DSSAT is primarily used on Windows.
        Users on other platforms should set dssat_executable explicitly in config.

        Returns:
            Path to DSSAT executable
        """
        # Check if explicitly configured
        pythia_config = None
        if self.config.platform_config and hasattr(self.config.platform_config, 'pythia'):
            pythia_config = self.config.platform_config.pythia

        if pythia_config and pythia_config.dssat_executable:
            return pythia_config.dssat_executable

        # Default to Windows path (most common use case for DSSAT)
        # Users on Mac/Linux should set dssat_executable in their config
        dssat_version = pythia_config.dssat_version if pythia_config else "4.8"
        version_num = dssat_version.replace(".", "")

        # Use standard Windows DSSAT installation path
        return f"C:/DSSAT{version_num}/DSCSM0{version_num}.EXE"

    def _doy_to_calendar_date(self, doy: int, year: int) -> str:
        """Convert day of year to calendar date string (YYYY-MM-DD).

        Args:
            doy: Day of year (1-365/366)
            year: Year for the date

        Returns:
            Date string in YYYY-MM-DD format
        """
        from datetime import timedelta
        dt = datetime(year, 1, 1) + timedelta(days=doy - 1)
        return dt.strftime("%Y-%m-%d")

    def _map_generic_to_pythia_config(self) -> Dict[str, Any]:
        """Map generic config to PYTHIA JSON default_setup parameters.

        Uses config.crop.phenology, config.crop.physiology, and config.management
        if available, otherwise uses defaults from PythiaConfig.

        Returns:
            Dictionary with PYTHIA-compatible parameter values
        """
        # Get PYTHIA-specific config
        pythia_config = None
        if self.config.platform_config and hasattr(self.config.platform_config, 'pythia'):
            pythia_config = self.config.platform_config.pythia

        # Get calendar from config
        calendar = self.config.crop.calendar
        if not calendar:
            raise ValueError("crop.calendar is required - planting_doy and maturity_doy must be specified")

        planting_doy = calendar.planting_doy

        # Get planting window from config (with fallback)
        planting_window = 30  # Default
        if pythia_config and hasattr(pythia_config, 'planting_window_days'):
            planting_window = pythia_config.planting_window_days

        # Get management config
        mgmt = self.config.management
        if mgmt is None:
            mgmt = ManagementConfig(planting_density=62500.0)

        # Get temporal config - REQUIRED
        if self.config.temporal:
            start_year = self.config.temporal.start_year
            end_year = self.config.temporal.end_year
            nyers = end_year - start_year + 1
        else:
            raise ValueError("temporal config is required - start_year and end_year must be specified")

        # Map irrigation setting
        if mgmt.irrigation:
            irrig = "A"  # Automatic irrigation
        else:
            irrig = "N"  # No irrigation (rainfed)

        # Get initial conditions from config (with fallbacks)
        ph2ol = 40.0
        icin = 10.0
        icsw_pct = 25.0
        icren = 0.8

        if pythia_config:
            if hasattr(pythia_config, 'soil_water_threshold'):
                ph2ol = pythia_config.soil_water_threshold
            if hasattr(pythia_config, 'initial_inorganic_n'):
                icin = pythia_config.initial_inorganic_n
            if hasattr(pythia_config, 'initial_soil_water_pct'):
                icsw_pct = pythia_config.initial_soil_water_pct
            if hasattr(pythia_config, 'residue_n_concentration'):
                icren = pythia_config.residue_n_concentration

        # Convert DOY to calendar dates (YYYY-MM-DD format for PYTHIA compatibility)
        pfrst_date = self._doy_to_calendar_date(planting_doy, start_year)
        plast_doy = min(planting_doy + planting_window, 365)
        plast_date = self._doy_to_calendar_date(plast_doy, start_year)

        return {
            # Temporal settings
            "nyers": nyers,
            "sdate": f"{start_year}-01-01",

            # Planting window (calendar date format: YYYY-MM-DD)
            "pfrst": pfrst_date,
            "plast": plast_date,

            # Soil moisture threshold for planting (%)
            "ph2ol": ph2ol,

            # Initial conditions
            "icin": icin,  # Initial inorganic N (kg/ha)
            "icsw%": icsw_pct,  # Initial soil water (%)
            "icren": icren,  # Residue N concentration

            # Flooding history (standard DSSAT defaults)
            "flhst": "FH302",
            "fhdur": 10,

            # Irrigation
            "irrig": irrig,
        }

    def _map_generic_to_cultivar(self) -> Dict[str, Any]:
        """Map generic phenology to DSSAT cultivar selection.

        Uses total thermal time (GDD) to select appropriate cultivar maturity class.
        For maize, this maps to DSSAT cultivar codes:
        - 990001: SHORT_SEASON (fast maturing)
        - 990002: MEDIUM_SEASON (intermediate)
        - 990003: LONG_SEASON (slow maturing)

        GDD thresholds are configurable via PythiaConfig.short_season_gdd_max
        and PythiaConfig.medium_season_gdd_max.

        Returns:
            Dictionary with cultivar parameters
        """
        pheno = self.config.crop.phenology

        # Use defaults if not provided
        if pheno is None:
            pheno = PhenologyConfig()

        # Calculate total thermal time requirement
        total_gdd = (
            pheno.emergence_gdd +
            pheno.vegetative_phase_gdd +
            pheno.reproductive_phase_gdd +
            pheno.grain_filling_gdd
        )

        # Get GDD thresholds from config (with defaults)
        short_gdd_max = 1400.0
        medium_gdd_max = 1700.0

        pythia_config = None
        if self.config.platform_config and hasattr(self.config.platform_config, 'pythia'):
            pythia_config = self.config.platform_config.pythia

        if pythia_config:
            if hasattr(pythia_config, 'short_season_gdd_max'):
                short_gdd_max = pythia_config.short_season_gdd_max
            if hasattr(pythia_config, 'medium_season_gdd_max'):
                medium_gdd_max = pythia_config.medium_season_gdd_max

        # Map to cultivar based on maturity (thermal time requirement)
        if total_gdd < short_gdd_max:
            # Short season / early maturing
            return {
                "ingeno": "990001",
                "cname": "SHORT_SEASON",
                "maturity_class": "early",
                "total_gdd": total_gdd,
            }
        elif total_gdd < medium_gdd_max:
            # Medium season / intermediate
            return {
                "ingeno": "990002",
                "cname": "MEDIUM_SEASON",
                "maturity_class": "medium",
                "total_gdd": total_gdd,
            }
        else:
            # Long season / late maturing
            return {
                "ingeno": "990003",
                "cname": "LONG_SEASON",
                "maturity_class": "late",
                "total_gdd": total_gdd,
            }

    def _map_generic_to_fertilizer(self) -> Dict[str, Any]:
        """Map generic management to fertilizer configuration.

        Uses ManagementConfig.fertilizer_n_total, fertilizer_n_splits,
        and fertilizer_n_fractions for full control over fertilization.

        Returns:
            Dictionary with fertilizer settings for PYTHIA
        """
        mgmt = self.config.management

        # Default values
        fen_tot = 60.0
        fer_dap = [0, 30]
        fer_pct = [50, 50]

        if mgmt is not None:
            # Get fertilizer total
            if hasattr(mgmt, 'fertilizer_n_total'):
                fen_tot = mgmt.fertilizer_n_total

            # Get application splits (days after planting)
            if hasattr(mgmt, 'fertilizer_n_splits'):
                fer_dap = mgmt.fertilizer_n_splits

            # Get application fractions
            if hasattr(mgmt, 'fertilizer_n_fractions'):
                # Convert fractions to percentages
                fer_pct = [int(f * 100) for f in mgmt.fertilizer_n_fractions]

        return {
            "fen_tot": fen_tot,
            "fer_dap": fer_dap,
            "fer_pct": fer_pct,
        }

    def _get_template_filename(self) -> str:
        """Get the actual template filename based on region and crop.

        Returns:
            Template filename (e.g., KOMZ8001.SNX)
        """
        region_code = self.config.region.name[:2].upper()
        crop_code = self.config.crop.name_short.upper()
        return f"{region_code}{crop_code}8001.SNX"

    # ISO3 to ISO2 country code mapping - comprehensive global coverage
    # Used for weather station prefixes and soil file lookups
    ISO3_TO_ISO2 = {
        # Africa
        "MLI": "ML", "BEN": "BJ", "NER": "NE", "BFA": "BF",
        "GHA": "GH", "TGO": "TG", "CIV": "CI", "SEN": "SN",
        "NGA": "NG", "CMR": "CM", "ETH": "ET", "KEN": "KE",
        "TZA": "TZ", "UGA": "UG", "ZAF": "ZA", "ZMB": "ZM",
        "ZWE": "ZW", "MOZ": "MZ", "MWI": "MW", "AGO": "AO",
        "DZA": "DZ", "EGY": "EG", "MAR": "MA", "TUN": "TN",
        "SDN": "SD", "SSD": "SS", "COD": "CD", "COG": "CG",
        "RWA": "RW", "BDI": "BI", "SOM": "SO", "ERI": "ER",
        "NAM": "NA", "BWA": "BW", "SWZ": "SZ", "LSO": "LS",
        "MDG": "MG", "MUS": "MU", "GMB": "GM", "GNB": "GW",
        "GIN": "GN", "SLE": "SL", "LBR": "LR", "CPV": "CV",
        "GAB": "GA", "GNQ": "GQ", "CAF": "CF", "TCD": "TD",
        # Asia
        "CHN": "CN", "IND": "IN", "IDN": "ID", "PAK": "PK",
        "BGD": "BD", "JPN": "JP", "PHL": "PH", "VNM": "VN",
        "THA": "TH", "MMR": "MM", "MYS": "MY", "KOR": "KR",
        "PRK": "KP", "NPL": "NP", "LKA": "LK", "KHM": "KH",
        "LAO": "LA", "AFG": "AF", "IRN": "IR", "IRQ": "IQ",
        "SAU": "SA", "YEM": "YE", "OMN": "OM", "ARE": "AE",
        "KAZ": "KZ", "UZB": "UZ", "TKM": "TM", "TJK": "TJ",
        "KGZ": "KG", "MNG": "MN", "TWN": "TW",
        # Americas
        "USA": "US", "CAN": "CA", "MEX": "MX", "BRA": "BR",
        "ARG": "AR", "COL": "CO", "PER": "PE", "VEN": "VE",
        "CHL": "CL", "ECU": "EC", "BOL": "BO", "PRY": "PY",
        "URY": "UY", "GUY": "GY", "SUR": "SR", "GTM": "GT",
        "HND": "HN", "NIC": "NI", "SLV": "SV", "CRI": "CR",
        "PAN": "PA", "CUB": "CU", "DOM": "DO", "HTI": "HT",
        "JAM": "JM",
        # Europe
        "DEU": "DE", "FRA": "FR", "GBR": "GB", "ITA": "IT",
        "ESP": "ES", "POL": "PL", "ROU": "RO", "NLD": "NL",
        "BEL": "BE", "GRC": "GR", "CZE": "CZ", "PRT": "PT",
        "HUN": "HU", "SWE": "SE", "AUT": "AT", "BGR": "BG",
        "DNK": "DK", "FIN": "FI", "SVK": "SK", "NOR": "NO",
        "IRL": "IE", "HRV": "HR", "LTU": "LT", "SVN": "SI",
        "LVA": "LV", "EST": "EE", "UKR": "UA", "BLR": "BY",
        "SRB": "RS", "CHE": "CH", "RUS": "RU", "TUR": "TR",
        # Oceania
        "AUS": "AU", "NZL": "NZ", "PNG": "PG", "FJI": "FJ",
    }

    def _iso3_to_iso2(self, iso3: str) -> str:
        """Convert ISO3 country code to ISO2.

        Args:
            iso3: 3-letter ISO country code (e.g., "MLI", "USA")

        Returns:
            2-letter ISO country code (e.g., "ML", "US")
        """
        if not iso3:
            return "XX"
        return self.ISO3_TO_ISO2.get(iso3, iso3[:2])

    def _get_wsta_prefix(self) -> str:
        """Get the weather station prefix for PYTHIA lookup.

        PYTHIA's lookup_wth function uses this prefix for output symlink naming.
        Format: 4-character code like "MLKO" (country + region).

        Returns:
            4-character weather station prefix (e.g., MLKO for Mali Koutiala)
        """
        country_iso3 = self.config.region.country_iso3 or ""
        region_name = self.config.region.name or ""

        country_code = self._iso3_to_iso2(country_iso3)

        # Build 4-char prefix: 2 chars country + 2 chars region
        region_code = region_name[:2].upper() if region_name else "XX"
        prefix = f"{country_code}{region_code}"[:4]

        return prefix

    def _generate_pythia_json(self, data: UnifiedData) -> Path:
        """Generate PYTHIA JSON configuration file.

        The JSON uses PYTHIA-specific function syntax:
        - xy_from_vector::path/to/shapefile
        - lookup_wth::SITE::vector::path::id_field
        - lookup_ghr::raster::path/to/soil_raster
        - raster::path/to/raster

        Uses generic config mapping when available (phenology, physiology, management).
        All paths are relative to package root (./) for portability.

        Args:
            data: UnifiedData with all configuration info

        Returns:
            Path to generated pythia_config.json
        """
        # Build RELATIVE file paths for portability
        # All paths start with ./ so package can be moved anywhere
        sites_file = "./shapes/sites.shp"
        weather_dir = "./weather/"
        soil_raster = "./raster/soil.tif"
        harvest_area = "./raster/harvest_area.tif"

        # Get parameters from generic config mapping
        use_generic_mapping = (
            self.config.crop.phenology is not None or
            self.config.crop.physiology is not None or
            self.config.management is not None
        )

        if use_generic_mapping:
            logger.info("Using generic config mapping for PYTHIA JSON")
            config_params = self._map_generic_to_pythia_config()
            cultivar_params = self._map_generic_to_cultivar()
            fertilizer_params = self._map_generic_to_fertilizer()

            nyers = config_params["nyers"]
            sdate = config_params["sdate"]
            pfrst = config_params["pfrst"]
            plast = config_params["plast"]
            irrig = config_params["irrig"]
            fen_tot = fertilizer_params["fen_tot"]
            ingeno = cultivar_params["ingeno"]
            cname = cultivar_params["cname"]

            logger.info(f"  Cultivar: {ingeno} ({cname}) - {cultivar_params['total_gdd']} GDD")
            logger.info(f"  Planting: {pfrst} to {plast}")
            logger.info(f"  Fertilizer: {fen_tot} kg N/ha")
            logger.info(f"  Irrigation: {irrig}")
        else:
            # Fallback - still use config values where available
            logger.info("No generic phenology/physiology config - using crop calendar and defaults")

            # Get date range - REQUIRED
            if self.config.temporal:
                start_year = self.config.temporal.start_year
                end_year = self.config.temporal.end_year
                nyers = end_year - start_year + 1
                sdate = f"{start_year}-01-01"
            else:
                raise ValueError(
                    "temporal config is required - please specify start_year and end_year in your config file"
                )

            # Get crop calendar - REQUIRED
            if self.config.crop.calendar:
                planting_doy = self.config.crop.calendar.planting_doy
                # Get planting window from pythia config
                pythia_cfg = self.config.platform_config.pythia if self.config.platform_config else None
                planting_window = 30
                if pythia_cfg and hasattr(pythia_cfg, 'planting_window_days'):
                    planting_window = pythia_cfg.planting_window_days
                # Convert DOY to calendar dates (YYYY-MM-DD format)
                pfrst = self._doy_to_calendar_date(planting_doy, start_year)
                plast_doy = min(planting_doy + planting_window, 365)
                plast = self._doy_to_calendar_date(plast_doy, start_year)
            else:
                raise ValueError(
                    "crop.calendar is required - please specify planting_doy and maturity_doy in your config file"
                )

            # Get management settings
            mgmt = self.config.management
            irrig = "A" if mgmt and mgmt.irrigation else "N"
            fen_tot = mgmt.fertilizer_n_total if mgmt and hasattr(mgmt, 'fertilizer_n_total') else 60

            # Use default cultivar mapping (medium season)
            ingeno = "990002"
            cname = "MEDIUM_SEASON"

        # Get start year for runs
        start_year = int(sdate.split("-")[0])

        # Get threading settings from config
        pythia_config = None
        if self.config.platform_config and hasattr(self.config.platform_config, 'pythia'):
            pythia_config = self.config.platform_config.pythia

        threads = pythia_config.threads if pythia_config and hasattr(pythia_config, 'threads') else 2
        cores = pythia_config.cores if pythia_config and hasattr(pythia_config, 'cores') else 4

        # Build PYTHIA JSON structure
        # All paths are relative (./) for portability - package can be moved anywhere
        pythia_json = {
            "name": self.config.project.name,
            "workDir": "./",
            "templateDir": "./templates/",
            "weatherDir": weather_dir,
            "threads": threads,
            "cores": cores,
            "ghr_root": "./eGHR/",  # eGHR data included in package

            "default_setup": {
                "template": self._get_template_filename(),
                "sites": f"xy_from_vector::{sites_file}",
                "nyers": nyers,
                "sdate": sdate,
                "pfrst": pfrst,
                "plast": plast,
                "ph2ol": 40,
                "icin": 10,
                "icsw%": 25,
                "icren": 0.8,
                "flhst": "FH302",
                "fhdur": 10,
                "id_soil": f"lookup_ghr::raster::{soil_raster}",
                "wsta": f"lookup_wth::{self._get_wsta_prefix()}::vector::{sites_file}::ID",
                "ic_layers": "generate_ic_layers::$id_soil",
                "irrig": irrig,
                "ingeno": ingeno,
                "cname": cname,
            },

            "dssat": {
                "executable": self._get_dssat_executable()
            },

            "analytics_setup": {
                "per_pixel_prefix": "output",
                "singleOutput": True
            },

            "runs": []
        }

        # Add runs/scenarios
        crop_name = self.config.crop.name

        # Baseline run (no fertilizer)
        run_baseline = {
            "name": f"{crop_name}_baseline",
            "harvestArea": f"raster::{harvest_area}",
            "startYear": start_year,
            "fen_tot": 0,
            "irrig": irrig,
            "ingeno": ingeno,
            "cname": f"{cname}_BASELINE",
        }
        pythia_json["runs"].append(run_baseline)

        # Fertilized scenario (using mapped fen_tot)
        run_fert = {
            "name": f"{crop_name}_fertilized",
            "harvestArea": f"raster::{harvest_area}",
            "startYear": start_year,
            "fen_tot": fen_tot,
            "irrig": irrig,
            "ingeno": ingeno,
            "cname": f"{cname}_FERTILIZED",
        }
        pythia_json["runs"].append(run_fert)

        # Write JSON file
        config_path = self.output_dir / "config" / "pythia_config.json"
        with open(config_path, 'w') as f:
            json.dump(pythia_json, f, indent='\t')

        logger.info(f"Generated PYTHIA JSON config: {config_path}")
        return config_path

    # =========================================================================
    # Raster Clipping Methods
    # =========================================================================

    def _clip_global_raster(
        self,
        input_path: Path,
        output_path: Path,
        bounds: Tuple[float, float, float, float],
        buffer: float = 0.1,
    ) -> Path:
        """Clip a global raster to region bounds.

        Reuses the pattern from eGHR source.

        Args:
            input_path: Path to input global raster
            output_path: Path to save clipped raster
            bounds: Tuple of (minx, miny, maxx, maxy)
            buffer: Buffer to add to bounds in degrees

        Returns:
            Path to clipped raster
        """
        import rasterio
        from rasterio.windows import from_bounds

        minx, miny, maxx, maxy = bounds
        minx -= buffer
        miny -= buffer
        maxx += buffer
        maxy += buffer

        output_path.parent.mkdir(parents=True, exist_ok=True)

        with rasterio.open(input_path) as src:
            # Create window from bounds
            window = from_bounds(minx, miny, maxx, maxy, src.transform)
            window = window.round_offsets().round_lengths()

            # Read data in window
            data = src.read(1, window=window)
            transform = src.window_transform(window)

            # Prepare output metadata
            meta = src.meta.copy()
            meta.update({
                'height': data.shape[0],
                'width': data.shape[1],
                'transform': transform,
            })

            # Write clipped raster
            with rasterio.open(output_path, 'w', **meta) as dst:
                dst.write(data, 1)

        logger.info(f"Clipped raster to {output_path} ({data.shape[1]}x{data.shape[0]} pixels)")
        return output_path

    def _generate_soil_raster(self, data: UnifiedData) -> Optional[Path]:
        """Clip eGHR soil raster to region bounds.

        Args:
            data: UnifiedData with grid info

        Returns:
            Path to soil raster or None if not configured
        """
        # Get eGHR raster path from config
        pythia_config = None
        if self.config.platform_config and hasattr(self.config.platform_config, 'pythia'):
            pythia_config = self.config.platform_config.pythia

        if not pythia_config or not pythia_config.eghr_raster_path:
            logger.warning("eGHR raster path not configured, skipping soil raster generation")
            return None

        # Resolve path relative to project root
        eghr_path = Path(pythia_config.eghr_raster_path)
        if not eghr_path.is_absolute():
            # Try to resolve relative to project root
            project_root = Path(__file__).parent.parent.parent.parent
            eghr_path = project_root / eghr_path

        if not eghr_path.exists():
            logger.error(f"eGHR raster not found: {eghr_path}")
            return None

        # Calculate bounds from grid
        if data.grid and data.grid.cells:
            lats = [cell.lat for cell in data.grid.cells]
            lons = [cell.lon for cell in data.grid.cells]
            bounds = (min(lons), min(lats), max(lons), max(lats))
        else:
            logger.warning("No grid data, using region bounds")
            if hasattr(data.region.bounds, 'to_gis_format'):
                bounds = tuple(data.region.bounds.to_gis_format())
            else:
                # Fallback to manual bounds from config
                mb = self.config.region.boundary.manual_bounds
                if mb:
                    bounds = (mb.minx, mb.miny, mb.maxx, mb.maxy)
                else:
                    logger.error("Cannot determine region bounds")
                    return None

        # Output path
        output_path = self.output_dir / "raster" / "soil.tif"

        try:
            return self._clip_global_raster(eghr_path, output_path, bounds)
        except Exception as e:
            logger.error(f"Failed to clip soil raster: {e}")
            return None

    def _generate_crop_mask_raster(self, data: UnifiedData) -> Optional[Path]:
        """Clip SPAM 2020 harvest area raster to region bounds.

        Args:
            data: UnifiedData with grid info

        Returns:
            Path to crop mask raster or None if not configured
        """
        # Get SPAM raster directory from config
        pythia_config = None
        if self.config.platform_config and hasattr(self.config.platform_config, 'pythia'):
            pythia_config = self.config.platform_config.pythia

        if not pythia_config or not pythia_config.spam_raster_dir:
            logger.warning("SPAM raster directory not configured, skipping crop mask generation")
            return None

        # Get SPAM crop code from crop name
        crop_code = self._get_spam_crop_code()
        spam_version = pythia_config.spam_version or "2020"

        # Build SPAM raster filename
        if spam_version == "2020":
            spam_filename = f"spam2020_V2r0_global_H_{crop_code}_A.tif"
        else:
            spam_filename = f"spam2010V2r0_global_H_{crop_code}_A.tif"

        # Resolve path
        spam_dir = Path(pythia_config.spam_raster_dir)
        if not spam_dir.is_absolute():
            project_root = Path(__file__).parent.parent.parent.parent
            spam_dir = project_root / spam_dir

        spam_path = spam_dir / spam_filename

        if not spam_path.exists():
            logger.error(f"SPAM raster not found: {spam_path}")
            return None

        # Calculate bounds from grid
        if data.grid and data.grid.cells:
            lats = [cell.lat for cell in data.grid.cells]
            lons = [cell.lon for cell in data.grid.cells]
            bounds = (min(lons), min(lats), max(lons), max(lats))
        else:
            logger.warning("No grid data, using region bounds")
            if hasattr(data.region.bounds, 'to_gis_format'):
                bounds = tuple(data.region.bounds.to_gis_format())
            else:
                mb = self.config.region.boundary.manual_bounds
                if mb:
                    bounds = (mb.minx, mb.miny, mb.maxx, mb.maxy)
                else:
                    logger.error("Cannot determine region bounds")
                    return None

        # Output path
        output_path = self.output_dir / "raster" / "harvest_area.tif"

        try:
            return self._clip_global_raster(spam_path, output_path, bounds)
        except Exception as e:
            logger.error(f"Failed to clip SPAM raster: {e}")
            return None

    def _get_spam_crop_code(self) -> str:
        """Get SPAM crop code from config or auto-detect from crop name.

        Priority:
        1. Explicit spam_crop_code in PythiaConfig
        2. Auto-detect from crop name using lookup table
        3. Warning if unknown crop (falls back to crop name uppercase)

        Returns:
            4-letter SPAM crop code (e.g., MAIZ, RICE)
        """
        # Check for explicit override in config
        pythia_config = None
        if self.config.platform_config and hasattr(self.config.platform_config, 'pythia'):
            pythia_config = self.config.platform_config.pythia

        if pythia_config and pythia_config.spam_crop_code:
            return pythia_config.spam_crop_code

        # Auto-detect from crop name
        crop_name = self.config.crop.name.lower()

        # Mapping of crop names to SPAM codes
        crop_map = {
            "maize": "MAIZ",
            "corn": "MAIZ",
            "rice": "RICE",
            "wheat": "WHEA",
            "sorghum": "SORG",
            "millet": "PMIL",
            "pearl millet": "PMIL",
            "barley": "BARL",
            "cassava": "CASS",
            "groundnut": "GROU",
            "peanut": "GROU",
            "soybean": "SOYB",
            "soy": "SOYB",
            "cotton": "COTT",
            "sugarcane": "SUGC",
            "sugar cane": "SUGC",
            "potato": "POTA",
            "sweet potato": "SWPO",
            "bean": "BEAN",
            "beans": "BEAN",
            "chickpea": "CHIC",
            "cowpea": "COWP",
            "lentil": "LENT",
            "pigeon pea": "PIGE",
            "sunflower": "SUNF",
            "rapeseed": "RAPE",
            "canola": "RAPE",
        }

        spam_code = crop_map.get(crop_name)

        if spam_code is None:
            # Warn user and try to construct a code
            logger.warning(
                f"Unknown crop '{crop_name}' for SPAM lookup. "
                f"Consider setting pythia.spam_crop_code in config. "
                f"Known crops: {', '.join(sorted(set(crop_map.values())))}"
            )
            # Try to use the crop short name as fallback
            spam_code = self.config.crop.name_short.upper()[:4]
            logger.warning(f"Using '{spam_code}' as SPAM code fallback")

        return spam_code

    # =========================================================================
    # eGHR Data Inclusion
    # =========================================================================

    def _get_required_country_codes(self) -> set:
        """Determine which country codes are needed based on soil raster pixels.

        Reads the clipped soil raster, looks up pixel IDs in GHR.db to find
        the country codes (2-letter ISO codes from profile names like ML04002407).

        Returns:
            Set of 2-letter country codes needed for the modeling area
        """
        import sqlite3

        country_codes = set()

        # Get soil raster path
        soil_raster = self.output_dir / "raster" / "soil.tif"
        if not soil_raster.exists():
            logger.warning("Soil raster not found, falling back to region country")
            # Fallback: use the config's country ISO code
            iso3 = self.config.region.country_iso3
            if iso3:
                iso2 = self._iso3_to_iso2(iso3)
                country_codes.add(iso2)
            return country_codes

        # Get GHR.db path
        pythia_config = self.config.platform_config.pythia if self.config.platform_config else None
        if not pythia_config or not pythia_config.eghr_database_path:
            return country_codes

        db_path = Path(pythia_config.eghr_database_path)
        if not db_path.is_absolute():
            project_root = Path(__file__).parent.parent.parent.parent
            db_path = project_root / db_path

        if not db_path.exists():
            logger.warning(f"GHR.db not found at {db_path}")
            return country_codes

        try:
            import rasterio
            import numpy as np

            # Read unique pixel IDs from soil raster
            with rasterio.open(soil_raster) as src:
                data = src.read(1)
                # Get unique non-zero pixel IDs
                unique_pixels = np.unique(data[data > 0])

            if len(unique_pixels) == 0:
                logger.warning("No valid pixel IDs in soil raster")
                return country_codes

            logger.info(f"Found {len(unique_pixels)} unique soil pixels in modeling area")

            # Query GHR.db for profile names (which contain country codes)
            conn = sqlite3.connect(str(db_path))
            cursor = conn.cursor()

            # Query in batches to avoid huge IN clauses
            batch_size = 1000
            for i in range(0, len(unique_pixels), batch_size):
                batch = unique_pixels[i:i+batch_size]
                placeholders = ','.join('?' * len(batch))
                cursor.execute(
                    f"SELECT DISTINCT profile FROM profile_map WHERE id IN ({placeholders})",
                    batch.tolist()
                )
                for row in cursor.fetchall():
                    profile = row[0]
                    if profile and len(profile) >= 2:
                        # Profile format: ML04002407 - first 2 chars are country code
                        country_code = profile[:2].upper()
                        country_codes.add(country_code)

            conn.close()

            logger.info(f"Countries covered by modeling area: {sorted(country_codes)}")

        except Exception as e:
            logger.warning(f"Error determining country codes: {e}")
            # Fallback to region country
            iso3 = self.config.region.country_iso3
            if iso3:
                country_codes.add(iso3[:2])

        return country_codes

    def _include_eghr_data(self) -> Optional[Path]:
        """Copy eGHR data (GHR.db and country-specific .SOL files) into package.

        This makes the package fully self-contained without external dependencies.
        Only includes .SOL files for countries covered by the modeling area.

        Returns:
            Path to eGHR directory in package, or None if not configured
        """
        import shutil

        # Get pythia config
        pythia_config = None
        if self.config.platform_config and hasattr(self.config.platform_config, 'pythia'):
            pythia_config = self.config.platform_config.pythia

        if not pythia_config:
            logger.warning("No PYTHIA config available, skipping eGHR data inclusion")
            return None

        # Determine which countries are needed
        required_countries = self._get_required_country_codes()
        if not required_countries:
            logger.warning("No country codes determined, skipping eGHR data inclusion")
            return None

        # Create eGHR directory in package
        eghr_output = self.output_dir / "eGHR"
        eghr_output.mkdir(parents=True, exist_ok=True)

        files_copied = 0

        # Copy GHR.db
        if pythia_config.eghr_database_path:
            src_db = Path(pythia_config.eghr_database_path)
            # Resolve relative path
            if not src_db.is_absolute():
                project_root = Path(__file__).parent.parent.parent.parent
                src_db = project_root / src_db

            if src_db.exists():
                dst_db = eghr_output / "GHR.db"
                shutil.copy2(src_db, dst_db)
                files_copied += 1
                logger.info(f"Copied GHR.db to package ({src_db.stat().st_size / 1024 / 1024:.1f} MB)")
            else:
                logger.warning(f"GHR.db not found at {src_db}")

        # Copy only required .SOL files (filtered by country)
        if pythia_config.eghr_sol_dir:
            src_sol_dir = Path(pythia_config.eghr_sol_dir)
            # Resolve relative path
            if not src_sol_dir.is_absolute():
                project_root = Path(__file__).parent.parent.parent.parent
                src_sol_dir = project_root / src_sol_dir

            if src_sol_dir.exists():
                sol_files_copied = 0
                total_size = 0

                for country_code in required_countries:
                    sol_file = src_sol_dir / f"{country_code}.SOL"
                    if sol_file.exists():
                        dst_sol = eghr_output / sol_file.name
                        shutil.copy2(sol_file, dst_sol)
                        sol_files_copied += 1
                        files_copied += 1
                        total_size += sol_file.stat().st_size
                        logger.debug(f"Copied {sol_file.name} ({sol_file.stat().st_size / 1024 / 1024:.1f} MB)")
                    else:
                        logger.warning(f"SOL file not found for country {country_code}: {sol_file}")

                logger.info(f"Copied {sol_files_copied} .SOL files for countries: {sorted(required_countries)} "
                           f"({total_size / 1024 / 1024:.1f} MB total)")
            else:
                logger.warning(f"eGHR SOL directory not found at {src_sol_dir}")

        if files_copied > 0:
            logger.info(f"eGHR data included in package: {eghr_output} ({files_copied} files)")
            return eghr_output
        else:
            logger.warning("No eGHR data files were copied")
            return None

    # =========================================================================
    # Weather Download Methods
    # =========================================================================

    def _download_site_weather(
        self,
        data: UnifiedData,
        progress_callback: Optional[callable] = None,
    ) -> Dict[int, 'ClimateTimeSeries']:
        """Download NASA POWER weather data for all grid sites.

        Args:
            data: UnifiedData with grid info
            progress_callback: Optional callback(current, total) for progress

        Returns:
            Dictionary mapping site_id to ClimateTimeSeries
        """
        from prismpy.sources.climate.nasa_power import NASAPowerSource, NASAPowerConfig

        # Get config settings
        pythia_config = None
        if self.config.platform_config and hasattr(self.config.platform_config, 'pythia'):
            pythia_config = self.config.platform_config.pythia

        # Determine date range - REQUIRED from config
        if pythia_config and pythia_config.climate_start_date:
            start_date = pythia_config.climate_start_date
        elif self.config.temporal:
            start_date = f"{self.config.temporal.start_year}-01-01"
        else:
            raise ValueError(
                "temporal.start_year or platform_config.pythia.climate_start_date is required. "
                "Please specify the simulation period in your config file."
            )

        if pythia_config and pythia_config.climate_end_date:
            end_date = pythia_config.climate_end_date
        elif self.config.temporal:
            end_date = f"{self.config.temporal.end_year}-12-31"
        else:
            raise ValueError(
                "temporal.end_year or platform_config.pythia.climate_end_date is required. "
                "Please specify the simulation period in your config file."
            )

        # Get delay setting
        delay = 2.0
        if pythia_config and hasattr(pythia_config, 'weather_download_delay'):
            delay = pythia_config.weather_download_delay

        # Initialize NASA POWER source with rate limiting
        nasa_config = NASAPowerConfig(
            request_delay=delay,
            retry_count=3,
            timeout=120,
        )
        source = NASAPowerSource(config=nasa_config)

        # Download for each grid cell
        climate_data = {}
        cells = data.grid.cells if data.grid else []
        total = len(cells)

        logger.info(f"Downloading NASA POWER weather for {total} sites ({start_date} to {end_date})")

        for i, cell in enumerate(cells):
            site_id = cell.cell_id

            if progress_callback:
                progress_callback(i + 1, total)

            logger.info(f"Downloading weather for site {site_id} ({i+1}/{total}): "
                        f"({cell.lat:.4f}, {cell.lon:.4f})")

            try:
                result = source.retrieve(
                    lat=cell.lat,
                    lon=cell.lon,
                    start_date=start_date,
                    end_date=end_date,
                    location_id=site_id,
                    use_cache=True,  # Use caching to speed up repeat runs
                )

                if result.success and result.data:
                    # Update location ID in the ClimateTimeSeries
                    result.data.location_id = site_id
                    climate_data[site_id] = result.data
                else:
                    logger.warning(f"Failed to download weather for site {site_id}: {result.errors}")

            except Exception as e:
                logger.error(f"Exception downloading weather for site {site_id}: {e}")

            # Rate limiting (already built into NASAPowerSource, but add explicit delay)
            if i < total - 1:
                time.sleep(delay)

        logger.info(f"Downloaded weather for {len(climate_data)}/{total} sites")
        return climate_data

    # =========================================================================
    # SNX Template Generation
    # =========================================================================

    def _generate_snx_template(self, data: UnifiedData) -> Path:
        """Generate DSSAT SNX experiment template with Jinja2 variables.

        Args:
            data: UnifiedData with region and config info

        Returns:
            Path to generated SNX template
        """
        # Generate experiment ID
        region_code = data.region.name[:2].upper()
        crop_code = self.config.crop.name_short.upper()
        exp_id = f"{region_code}{crop_code}8001"

        # Get mapped parameters
        config_params = self._map_generic_to_pythia_config()
        cultivar_params = self._map_generic_to_cultivar()
        fertilizer_params = self._map_generic_to_fertilizer()

        # Get management config for planting parameters
        mgmt = self.config.management
        planting_density = mgmt.planting_density if mgmt else 62500.0
        row_spacing = mgmt.row_spacing_cm if mgmt and hasattr(mgmt, 'row_spacing_cm') else 70.0

        # Calculate plants per m2 (PPOP in DSSAT is plants/m2)
        ppop = planting_density / 10000.0  # Convert plants/ha to plants/m2

        # Build SNX content
        template_content = self._build_snx_content(
            exp_id=exp_id,
            region_name=data.region.name,
            country=data.region.country,
            crop_name=self.config.crop.name,
            cultivar=cultivar_params,
            fertilizer=fertilizer_params,
            config=config_params,
            ppop=ppop,
            row_spacing=row_spacing,
        )

        # Create templates directory
        templates_dir = self.output_dir / "templates"
        templates_dir.mkdir(parents=True, exist_ok=True)

        # Write template
        template_path = templates_dir / f"{exp_id}.SNX"
        with open(template_path, 'w') as f:
            f.write(template_content)

        logger.info(f"Generated SNX template: {template_path}")
        return template_path

    def _build_snx_content(
        self,
        exp_id: str,
        region_name: str,
        country: str,
        crop_name: str,
        cultivar: Dict[str, Any],
        fertilizer: Dict[str, Any],
        config: Dict[str, Any],
        ppop: float = 5.0,
        row_spacing: float = 70.0,
    ) -> str:
        """Build SNX file content with Jinja2 placeholders.

        This creates a DSSAT experiment file template that PYTHIA will
        fill in with site-specific values at runtime.

        DSSAT SNX format requirements:
        - TNAME field must be exactly 25 characters
        - MF (fertilizer level) must be 0 if no fertilizers applied
        - RAMT (residue amount) must be a valid value (not -99)

        Args:
            exp_id: Experiment ID (e.g., MLMZ8001)
            region_name: Region name
            country: Country name
            crop_name: Crop name
            cultivar: Cultivar parameters
            fertilizer: Fertilizer parameters
            config: PYTHIA config parameters
            ppop: Plant population (plants/m2)
            row_spacing: Row spacing (cm)

        Returns:
            SNX file content as string
        """
        # Get DSSAT crop code
        crop_code = self.config.crop.name_short.upper()[:2]

        # Build treatment name - must be exactly 25 characters
        # Format: "{crop_name} rainfed" padded to 25 chars
        base_tname = f"{crop_name} rainfed"
        tname = base_tname[:25].ljust(25)  # Truncate if too long, pad if too short

        # Get residue amount from config or use sensible default
        # DSSAT requires a valid value (not -99)
        # Default: 250 kg/ha (typical crop residue incorporation)
        mgmt = self.config.management
        residue_amount = 250  # Default: standard residue amount
        if mgmt and hasattr(mgmt, 'residue_amount_kg_ha'):
            residue_amount = int(mgmt.residue_amount_kg_ha)

        content = f"""*EXP.DETAILS: {exp_id}{crop_code} {country} {region_name}, {crop_name} management scenarios

*GENERAL
@PEOPLE
 prismpy automated
@ADDRESS
 Generated by prismpy
@SITE
 {region_name} Region, {country}

*TREATMENTS                        -------------FACTOR LEVELS------------
@N R O C TNAME.................... CU FL SA IC MP MI MF MR MC MT ME MH SM
 1 1 1 0 {tname} 1  1  0  1  1  0 {{% if fertilizers %}}1{{% else %}}0{{% endif %}}  1  0  0  0  0  1

*CULTIVARS
@C CR INGENO CNAME
 1 {crop_code} {{{{ ingeno }}}} {{{{ cname }}}}

*FIELDS
@L ID_FIELD WSTA....  FLSA  FLOB  FLDT  FLDD  FLDS  FLST SLTX  SLDP  ID_SOIL    FLNAME
 1 GENERIC2 {{{{ wsta }}}}   -99   -99   -99   -99   -99   -99 -99    -99  {{{{ id_soil }}}} {country} {crop_name} rainfed
@L ...........XCRD ...........YCRD .....ELEV .............AREA .SLEN .FLWR .SLAS FLHST FHDUR
 1 {{{{ xcrd }}}} {{{{ ycrd }}}}       -99               -99   -99   -99   -99 {{{{ flhst }}}} {{{{ fhdur }}}}

*INITIAL CONDITIONS
@C   PCR ICDAT  ICRT  ICND  ICRN  ICRE  ICWD ICRES ICREN ICREP ICRIP ICRID ICNAME
 1    {crop_code} {{{{ sdate }}}}{{{{ icrt }}}}   -99     1     1   -99{{{{ icres }}}}{{{{ icren }}}}   -99   100     5 rf
@C  ICBL  SH2O  SNH4  SNO3
{{% for layer in ic_layers %}}
 1{{{{ layer.icbl }}}}{{{{ layer.sh2o }}}}{{{{layer.snh4 }}}}{{{{ layer.sno3 }}}}
{{% endfor %}}

*PLANTING DETAILS
@P PDATE EDATE  PPOP  PPOE  PLME  PLDS  PLRS  PLRD  PLDP  PLWT  PAGE  PENV  PLPH  SPRL                        PLNAME
 1   -99   -99 {ppop:5.1f} {ppop:5.1f}     S     R {row_spacing:5.0f}   -99     5   -99   -99   -99   -99   -99                        auto

*FERTILIZERS (INORGANIC)
@F FDATE  FMCD  FACD  FDEP  FAMN  FAMP  FAMK  FAMC  FAMO  FOCD FERNAME
{{% for fert in fertilizers %}}
 1 {{{{ fert.fdap }}}} FE005 AP002     5 {{{{ fert.famn }}}}     0   -99   -99   -99   -99 Urea
{{% endfor %}}

*RESIDUES AND ORGANIC FERTILIZER
@R RDATE  RCOD  RAMT  RESN  RESP  RESK  RINP  RDEP  RMET RENAME
 1     0 RE003 {residue_amount:4d}   -99   -99   -99   -99   -99   -99 Residue application

*ENVIRONMENT MODIFICATIONS
@E ODATE EDAY  ERAD  EMAX  EMIN  ERAIN ECO2  EDEW  EWIND ENVNAME
 1 {{{{ sdate }}}} A   0 A   0 A   0 A   0 A   0 A   0 A   0 A   0 ENV modify

*SIMULATION CONTROLS
@N GENERAL     NYERS NREPS START SDATE RSEED SNAME.................... SMODEL
 1 GE          {{{{ nyers }}}}     1     S {{{{ sdate }}}}  2150 Rainfed                   {crop_code}CER
@N OPTIONS     WATER NITRO SYMBI PHOSP POTAS DISES  CHEM  TILL   CO2
 1 OP              Y     Y     N     N     N     N     N     N     M
@N METHODS     WTHER INCON LIGHT EVAPO INFIL PHOTO HYDRO NSWIT MESOM MESEV MESOL
 1 ME              M     M     E     R     S     L     R     1     P     S     2
@N MANAGEMENT  PLANT IRRIG FERTI RESID HARVS
 1 MA              F {{{{ irrig }}}}     D     D     M
@N OUTPUTS     FNAME OVVEW SUMRY FROPT GROUT CAOUT WAOUT NIOUT MIOUT DIOUT VBOSE CHOUT OPOUT FMOPT
 1 OU              N     N     Y    14     N     N     N     N     N     N     0     N     N     C

@  AUTOMATIC MANAGEMENT
@N PLANTING    PFRST PLAST PH2OL PH2OU PH2OD PSTMX PSTMN
 1 PL          {{{{ pfrst }}}} {{{{ plast }}}} {{{{ ph2ol }}}}   100    30    40    10
@N IRRIGATION  IMDEP ITHRL ITHRU IROFF IMETH IRAMT IREFF
 1 IR             30    50   100 GS000 IR001    10   1.0
@N NITROGEN    NMDEP NMTHR NAMNT NCODE NAOFF
 1 NI             30    10    50 FE001 GS000
@N RESIDUES    RIPCN RTIME RIDEP
 1 RE            100     1    20
@N HARVEST     HFRST HLAST HPCNP HPCNR
 1 HA              0 01096   100     0
"""
        return content

    # =========================================================================
    # Package Assembly Methods
    # =========================================================================

    def _generate_package_files(self, data: UnifiedData) -> List[Path]:
        """Generate package metadata files (manifest, provenance, README).

        Args:
            data: UnifiedData with region and config info

        Returns:
            List of generated file paths
        """
        from prismpy.packaging.manifest import create_manifest, save_manifest
        from prismpy.packaging.provenance import ProvenanceTracker, create_decision

        output_files = []

        # 1. Generate provenance.json
        provenance_path = self._generate_provenance(data)
        if provenance_path:
            output_files.append(provenance_path)

        # 2. Generate manifest.json
        manifest_path = self._generate_manifest(data)
        if manifest_path:
            output_files.append(manifest_path)

        # 3. Generate README.md
        readme_path = self._generate_readme(data)
        if readme_path:
            output_files.append(readme_path)

        return output_files

    def _generate_provenance(self, data: UnifiedData) -> Path:
        """Generate provenance.json tracking data sources and decisions.

        Uses stage-based format matching SARRA-Py pattern:
        - RETRIEVE: Site coordinates, boundary source
        - HARMONIZE: Climate (NASA POWER), Soil (eGHR)
        - TRANSLATE: SNX templates, experiment config

        Args:
            data: UnifiedData with region info

        Returns:
            Path to provenance.json
        """
        from prismpy.packaging.provenance import ProvenanceTracker, create_decision

        # Create tracker
        session_id = f"pythia_{data.region.name.lower()}_{datetime.now():%Y%m%d_%H%M%S}"
        tracker = ProvenanceTracker(session_id=session_id, workflow="prismpy_pythia")

        # Get bounds info
        if hasattr(data.region.bounds, 'to_gis_format'):
            bounds = data.region.bounds.to_gis_format()
        else:
            bounds = [data.region.bounds.minx, data.region.bounds.miny,
                     data.region.bounds.maxx, data.region.bounds.maxy]

        # Stage 1: RETRIEVE - Site coordinates and boundary source
        tracker.add_stage(
            stage_name="RETRIEVE",
            inputs={
                "region": data.region.name,
                "country": data.region.country,
                "bounds": bounds,
                "boundary_source": "GADM v4.1",
            },
            outputs=[
                "shapes/sites.shp",
                "shapes/sites.shx",
                "shapes/sites.dbf",
                "shapes/sites.prj",
            ],
            decisions=[
                create_decision("BOUNDARY_SOURCE", "GADM v4.1",
                               "Administrative boundaries with polygon geometry",
                               alternatives=["Manual bounds", "Shapefile"]),
                create_decision("GRID_RESOLUTION", f"{self.config.platform_config.pythia.grid_resolution if self.config.platform_config and self.config.platform_config.pythia else 0.0833}°",
                               "~10km resolution matching legacy PYTHIA"),
            ],
            notes=f"Retrieved {len(data.grid.cells) if data.grid else 0} site locations for {data.region.name}"
        )

        # Stage 2: HARMONIZE - Climate and soil data processing
        n_weather = len(list((self.output_dir / "weather").glob("*.WTH"))) if (self.output_dir / "weather").exists() else 0
        n_sol = len(list((self.output_dir / "eGHR").glob("*.SOL"))) if (self.output_dir / "eGHR").exists() else 0

        tracker.add_stage(
            stage_name="HARMONIZE",
            inputs={
                "climate_source": "NASA POWER API",
                "soil_source": "eGHR (GGCMI Soils v2)",
                "crop_mask_source": "SPAM 2020 v2.0",
            },
            outputs=[
                "weather/*.WTH",
                "raster/soil.tif",
                "raster/harvest_area.tif",
                "eGHR/GHR.db",
                "eGHR/*.SOL",
            ],
            decisions=[
                create_decision("WEATHER_SOURCE", "NASA POWER",
                               f"Downloaded {n_weather} .WTH files with daily SRAD, TMAX, TMIN, RAIN, TDEW, RHUM, WIND",
                               alternatives=["AgERA5", "CHIRPS+ERA5"]),
                create_decision("SOIL_SOURCE", "eGHR",
                               f"Clipped soil raster + {n_sol} country-specific .SOL profiles",
                               alternatives=["HWSD", "SoilGrids", "iSDA"]),
                create_decision("CROP_MASK", "SPAM 2020 v2.0",
                               "Harvested area raster for yield weighting",
                               alternatives=["SPAM 2010"]),
            ],
            notes=f"Harmonized data for {data.region.name}: {n_weather} weather files, {n_sol} soil profiles"
        )

        # Stage 3: TRANSLATE - SNX templates and experiment config
        cultivar = self._map_generic_to_cultivar()
        fertilizer = self._map_generic_to_fertilizer()

        tracker.add_stage(
            stage_name="TRANSLATE",
            inputs={
                "unified_data": "internal",
                "platform": "pythia",
            },
            outputs=[
                f"templates/{self._get_template_filename()}",
                "config/pythia_config.json",
                "raster/fertilizer.tif",
                "raster/planting_doy.tif",
                "raster/cultivar.tif",
            ],
            decisions=[
                create_decision("OUTPUT_FORMAT", "PYTHIA/DSSAT",
                               "Spatial DSSAT simulation package with JSON config and SNX template"),
                create_decision("CULTIVAR_MAPPING", cultivar.get("ingeno", "990002"),
                               f"Mapped from phenology: {cultivar.get('total_gdd', 'N/A')} GDD → {cultivar.get('cname', 'MEDIUM_SEASON')}"),
                create_decision("FERTILIZER_REGIME", f"{fertilizer.get('fen_tot', 60)} kg N/ha",
                               f"Split application: {fertilizer.get('fer_pct', [50, 50])}"),
            ],
            notes=f"Generated PYTHIA package with template {self._get_template_filename()}"
        )

        # Save
        provenance_path = self.output_dir / "provenance.json"
        tracker.save(provenance_path)

        logger.info(f"Generated provenance: {provenance_path}")
        return provenance_path

    def _generate_manifest(self, data: UnifiedData) -> Path:
        """Generate manifest.json with file inventory and checksums.

        Args:
            data: UnifiedData with region info

        Returns:
            Path to manifest.json
        """
        from prismpy.packaging.manifest import create_manifest, save_manifest

        # Build project config for manifest
        project_config = {
            "project_name": self.config.project.name,
            "region_name": data.region.name,
            "country": data.region.country,
            "gadm_level": self.config.region.boundary.gadm_level or 2,
            "crop_name": self.config.crop.name,
            "planting_doy": self.config.crop.calendar.planting_doy if self.config.crop.calendar else None,
            "maturity_doy": self.config.crop.calendar.maturity_doy if self.config.crop.calendar else None,
            "start_year": self.config.temporal.start_year if self.config.temporal else None,
            "end_year": self.config.temporal.end_year if self.config.temporal else None,
            "spinup_years": self.config.temporal.spinup_years if self.config.temporal else 0,
            "data_sources": {
                "climate": "NASA POWER",
                "soil": "eGHR",
                "crop_mask": "SPAM 2020",
            }
        }

        # Create manifest
        manifest = create_manifest(
            package_dir=self.output_dir,
            project_config=project_config,
            platform="pythia",
        )

        # Save
        manifest_path = self.output_dir / "manifest.json"
        save_manifest(manifest, manifest_path)

        logger.info(f"Generated manifest: {manifest_path}")
        return manifest_path

    def _generate_readme(self, data: UnifiedData) -> Path:
        """Generate README.md using the centralized template.

        Args:
            data: UnifiedData with region info

        Returns:
            Path to README.md
        """
        from prismpy.packaging.readme_generator import generate_readme

        # Count files by type
        weather_count = len(list((self.output_dir / "weather").glob("*.WTH"))) if (self.output_dir / "weather").exists() else 0
        sol_count = len(list((self.output_dir / "eGHR").glob("*.SOL"))) if (self.output_dir / "eGHR").exists() else 0
        n_sites = len(data.grid.cells) if data.grid else 0

        # Get parameters
        cultivar = self._map_generic_to_cultivar()
        fertilizer = self._map_generic_to_fertilizer()
        config_params = self._map_generic_to_pythia_config()

        # Get management config
        mgmt = self.config.management
        plant_pop = mgmt.planting_density / 10000.0 if mgmt else 5.0
        row_spacing = mgmt.row_spacing_cm if mgmt and hasattr(mgmt, 'row_spacing_cm') else 70.0

        # Build config dictionary for template
        readme_config = {
            # Project info
            'project_name': self.config.project.name,
            'package_dir': self.output_dir.name,
            'region_name': data.region.name,
            'country': data.region.country,
            'crop_name': self.config.crop.name,
            'gadm_level': self.config.region.boundary.gadm_level or 2,

            # Temporal
            'start_year': self.config.temporal.start_year if self.config.temporal else 2010,
            'end_year': self.config.temporal.end_year if self.config.temporal else 2019,
            'n_years': (self.config.temporal.end_year - self.config.temporal.start_year + 1) if self.config.temporal else 10,

            # Package contents
            'n_sites': n_sites,
            'n_weather_files': weather_count,
            'n_sol_files': sol_count,
            'wsta_prefix': self._get_wsta_prefix(),
            'template_name': self._get_template_filename(),

            # Crop parameters
            'cultivar_code': cultivar.get('ingeno', '990002'),
            'cultivar_name': cultivar.get('cname', 'MEDIUM_SEASON'),
            'total_gdd': cultivar.get('total_gdd', 'N/A'),
            'pfrst': config_params.get('pfrst', 'N/A'),
            'plast': config_params.get('plast', 'N/A'),

            # Management settings
            'fen_tot': fertilizer.get('fen_tot', 60),
            'plant_pop': plant_pop,
            'row_spacing': row_spacing,
            'irrigation': 'Enabled' if mgmt and mgmt.irrigation else 'Rainfed',

            # Data sources
            'data_sources': {
                'climate': 'NASA POWER',
                'soil': 'eGHR (GGCMI)',
                'crop_mask': 'SPAM 2020',
                'boundaries': 'GADM v4.1',
            }
        }

        # Generate README using centralized template
        readme_path = self.output_dir / "README.md"
        generate_readme(readme_path, readme_config, platform="pythia")

        logger.info(f"Generated README: {readme_path}")
        return readme_path
