"""
README Generation for prismpy packages.

Provides template-based README generation for platform-specific packages.
"""

from datetime import datetime
from pathlib import Path
from typing import Any, Dict, Optional, Union


# SARRA-Py README template
SARRA_PY_README_TEMPLATE = '''# {project_name}

**SARRA-Py Input Data Package**

Generated by prismpy

## Quick Start

```python
# See full simulation script below
import datetime
from sarra_py import load_TAMSAT_data, run_model
```

---

## Package Overview

| Property | Value |
|----------|-------|
| **Region** | {region_name}, {country} |
| **Crop** | {crop_name} |
| **Period** | {start_year}-{end_year} |
| **Generated** | {generated_at} |

---

## Package Contents

```
{package_name}/
├── README.md                    # This file
├── manifest.json                # File inventory with SHA256 checksums
├── provenance.json              # Data sources and processing decisions
│
├── config/
│   └── project_config.yaml      # Full configuration
│
├── data/
│   ├── boundaries/
│   │   └── bounds.json          # Region bounding box
│   │
│   ├── climate/
│   │   ├── rainfall/            # TAMSAT v3.1 daily (GeoTIFF)
│   │   ├── 2m_temperature_24_hour_maximum/
│   │   ├── 2m_temperature_24_hour_mean/
│   │   ├── 2m_temperature_24_hour_minimum/
│   │   ├── ET0Hargeaves/
│   │   └── solar_radiation_flux_daily/
│   │
│   └── soil/
│       └── soil_params.yaml
│
├── parameters/
│   ├── variety.yaml             # Crop phenology & growth (52 params)
│   ├── itk.yaml                 # Agricultural itinerary (24 params)
│   └── soil.yaml                # Soil water balance (13 params)
│
└── validation/
    └── validation_report.json
```

---

## Data Sources

| Data Type | Source | Format | Resolution |
|-----------|--------|--------|------------|
| Boundaries | {boundary_source} | JSON | {admin_level_label} |
| Rainfall | {rainfall_source} | GeoTIFF | ~4km |
| Temperature | {temperature_source} | GeoTIFF | ~10km |
| Soil | {soil_source} | YAML | Regional |

---

## Running a SARRA-Py Simulation

### Prerequisites

```bash
pip install sarra-py xarray rioxarray rasterio pyyaml tqdm
```

### Complete Working Example

```python
#!/usr/bin/env python3
"""SARRA-Py Simulation using {package_name}"""

import os
import sys
import datetime
import yaml
import numpy as np
import xarray as xr
import rioxarray
import pandas as pd
from tqdm import tqdm

# Configuration - UPDATE THESE PATHS
PACKAGE_ROOT = "/path/to/{package_name}"
SARRA_PY_SRC = "/path/to/SARRA-Py/src"

sys.path.insert(0, SARRA_PY_SRC)

from sarra_py import (
    get_grid_size, load_TAMSAT_data, load_iSDA_soil_data,
    calc_day_length_raster_fast, initialize_simulation,
    initialize_default_irrigation, calculate_once_daily_thermal_time,
    run_model
)

# Paths
RAINFALL_PATH = os.path.join(PACKAGE_ROOT, "data/climate/rainfall")
CLIMATE_PATH = os.path.join(PACKAGE_ROOT, "data/climate")
PARAMS_PATH = os.path.join(PACKAGE_ROOT, "parameters")

# Simulation dates
date_start = datetime.date({start_year}, 5, 1)
duration = 200

def load_climate_from_package(data, climate_path, date_start, duration):
    """Load AgERA5 variables from package subdirectories."""
    var_mapping = {{
        '2m_temperature_24_hour_mean': 'tpMoy',
        'ET0Hargeaves': 'ET0',
        'solar_radiation_flux_daily': 'rg',
    }}

    for folder_name, sarra_name in var_mapping.items():
        var_path = os.path.join(climate_path, folder_name)
        files = sorted([f for f in os.listdir(var_path) if f.endswith('.tif')])

        file_df = pd.DataFrame({{"filename": files}})
        file_df["date"] = file_df["filename"].apply(
            lambda x: datetime.date(
                int(x.replace(".tif","").split("_")[-3]),
                int(x.replace(".tif","").split("_")[-2]),
                int(x.replace(".tif","").split("_")[-1])
            )
        )

        end_date = date_start + datetime.timedelta(days=duration)
        file_df = file_df[(file_df["date"] >= date_start) & (file_df["date"] < end_date)]

        arrays = []
        for _, row in tqdm(file_df.iterrows(), total=len(file_df), desc=folder_name):
            filepath = os.path.join(var_path, row["filename"])
            da = rioxarray.open_rasterio(filepath)
            da = da.rio.reproject_match(data, nodata=np.nan)
            da = da.squeeze("band").drop_vars(["band"])
            arrays.append(da)

        data[sarra_name] = xr.concat(arrays, "time")

    data["rg"] = data["rg"] / 1000  # kJ/m² -> MJ/m²/day
    return data

def load_params(params_path):
    """Load variety, ITK, and soil parameters."""
    with open(os.path.join(params_path, "variety.yaml")) as f:
        variety = yaml.safe_load(f)
    with open(os.path.join(params_path, "itk.yaml")) as f:
        itk = yaml.safe_load(f)
        if isinstance(itk.get("DateSemis"), str):
            itk["DateSemis"] = datetime.datetime.strptime(itk["DateSemis"], "%Y-%m-%d").date()
    with open(os.path.join(params_path, "soil.yaml")) as f:
        soil = yaml.safe_load(f)
    return variety, itk, soil

def run_simulation():
    print("Loading parameters...")
    paramVariete, paramITK, paramTypeSol = load_params(PARAMS_PATH)

    print("Getting grid dimensions...")
    grid_width, grid_height = get_grid_size(RAINFALL_PATH, date_start, duration)

    print("Loading climate data...")
    data = xr.Dataset()
    data = load_TAMSAT_data(data, RAINFALL_PATH, date_start, duration)
    data = load_climate_from_package(data, CLIMATE_PATH, date_start, duration)

    print("Loading soil and computing day length...")
    original_cwd = os.getcwd()
    os.chdir(os.path.join(SARRA_PY_SRC, "../notebooks"))
    data = load_iSDA_soil_data(data, grid_width, grid_height)
    os.chdir(original_cwd)
    data = calc_day_length_raster_fast(data, date_start, duration)

    print("Initializing and running simulation...")
    data = initialize_simulation(data, grid_width, grid_height, duration, paramVariete, paramITK, date_start)
    data = initialize_default_irrigation(data)
    data = calculate_once_daily_thermal_time(data, paramVariete)
    data = run_model(paramVariete, paramITK, paramTypeSol, data, duration)

    # Results
    final_yield = data["rdt"][-1, :, :]
    valid = final_yield.values[~np.isnan(final_yield.values)]
    print(f"\\nMean yield: {{np.mean(valid):.0f}} kg/ha")
    print(f"Yield range: {{np.min(valid):.0f}} - {{np.max(valid):.0f}} kg/ha")

    return data

if __name__ == "__main__":
    run_simulation()
```

---

## Parameter Files Reference

### variety.yaml - Crop Parameters (52 params)

| Parameter | Description |
|-----------|-------------|
| `TBase` | Base temperature (°C) |
| `TOpt1`, `TOpt2` | Optimal temperature range (°C) |
| `TLim` | Limiting temperature (°C) |
| `SDJLevee` | GDD to emergence |
| `SDJBVP` | GDD vegetative phase |
| `kcMax` | Max crop coefficient |

### itk.yaml - Agricultural Itinerary (24 params)

| Parameter | Description |
|-----------|-------------|
| `DateSemis` | Sowing date (YYYY-M-D) |
| `densite` | Plant density (plants/ha) |
| `seuilEauSemis` | Water threshold for emergence (mm) |
| `irrigAuto` | Automatic irrigation (true/false) |

### soil.yaml - Soil Parameters (13 params)

| Parameter | Description |
|-----------|-------------|
| `epaisseurSurf` | Surface layer depth (mm) |
| `epaisseurProf` | Deep layer depth (mm) |
| `ru` | Plant available water (mm) |
| `seuilRuiss` | Runoff threshold (mm) |

---

## Validation

This package was validated for:
- All required files present
- File checksums match manifest
- Parameter files are valid YAML
- Bounds cover expected region

See `validation/validation_report.json` for details.

---

## Troubleshooting

**Import error: No module named 'sarra_py'**
- Add SARRA-Py src folder to `sys.path` before importing

**Soil data loading fails**
- SARRA-Py requires asset files in `../data/assets/` relative to notebooks

**No yield output (all NaN)**
- Check that `DateSemis` falls within the simulation period

---

## Citation

```bibtex
@software{{prismpy,
  title = {{prismpy: Data-to-Model Translation for Crop Modeling}},
  year = {{2026}},
  note = {{Package generated: {generated_at}}}
}}
```

---

*Package version: 1.0 | Generator: prismpy v1.0.0*
'''


# CRAFT README template
CRAFT_README_TEMPLATE = '''# {project_name}

**CRAFT Model Input Data Package**

Generated by prismpy

---

## Quick Start

1. Copy schema files to `C:\\CCAFSToolkit\\CRAFT_Schema\\`
2. Copy `weather/input.csv` to `C:\\CCAFSToolkit\\Weather_By_Python\\`
3. Download weather via CRAFT GUI: Data -> Weather Data -> Download from NASA
4. Upload soil and management files
5. Configure simulation in CRAFT GUI

---

## Package Overview

| Property | Value |
|----------|-------|
| **Region** | {region_name}, {country} |
| **CRAFT Level** | Level {craft_level} |
| **Crop** | {crop_name} |
| **Period** | {start_year}-{end_year} |
| **Grid Cells** | {n_cells} |
| **Soil Profiles** | {n_soil_profiles} |
| **Generated** | {generated_at} |

---

## Package Contents

```
craft/
├── README.md                    # This file
├── manifest.json                # File inventory with SHA256 checksums
├── provenance.json              # Data sources and processing decisions
│
├── schema/
│   ├── 5m_area.txt              # Cell areas (copy to C:\\CCAFSToolkit\\)
│   ├── CRAFT_Schema/            # Copy to C:\\CCAFSToolkit\\CRAFT_Schema\\
│   │   └── Level{craft_level}/
│   │       ├── Schema/
│   │       │   └── 5m_{admin_names}.txt
│   │       └── Shape/           # Boundary shapefiles
│   └── Python_Schemas/          # For CRAFT Python scripts (folders 02-08)
│       └── Level{craft_level}/
│           └── Schema_{admin_names}.txt
│
├── weather/
│   └── input.csv                # NASA POWER download specification
│
├── soil/
│   ├── {country_code}.SOL       # DSSAT soil profiles
│   └── soil_mask.txt            # CellID → profile mapping
│
├── crop_mask/
│   └── mask.txt                 # Crop presence (CellId, Percent)
│
└── management/
    ├── cultivar_data.txt        # CellID → cultivar mapping
    ├── planting_data.txt        # Planting configuration (15 cols)
    ├── fertilizer_data.txt      # Inorganic fertilizer (14 cols)
    └── organic_fertilizer_data.txt  # Organic/residue (13 cols)
```

---

## Data Sources

| Data Type | Source | Description |
|-----------|--------|-------------|
| **Soil** | {soil_source} | {soil_description} |
| **Crop Mask** | {crop_mask_source} | {crop_mask_description} |
| **Boundaries** | {boundary_source} | {boundary_description} |
| **Climate** | NASA POWER | To be downloaded (SRAD, TMAX, TMIN, RAIN) |

---

## Importing into CRAFT

### Step 1: Install Schema Files

Copy the schema directory to CRAFT:

```
schema/CRAFT_Schema/  -->  C:\\CCAFSToolkit\\CRAFT_Schema\\
schema/5m_area.txt    -->  C:\\CCAFSToolkit\\5m_area.txt
```

This provides CRAFT with grid cell definitions (CELLID, SHAREPERCENT) and
boundary shapefiles for your study area.

### Step 2: Download Weather Data

The `weather/input.csv` file contains cell coordinates (CellID, Latitude,
Longitude) used by CRAFT's weather download scripts. It must be placed in the
correct location **before** triggering the download from CRAFT.

**Procedure:**

1. Copy `weather/input.csv` to `C:\\CCAFSToolkit\\Weather_By_Python\\`
2. Open CRAFT GUI -> Data -> Weather Data -> Download from NASA
3. Set start/end dates (NASA POWER SRAD data available from 1984-01-01)
4. Browse to the input file you just copied
5. Start download (expect ~45-75 min for ~150 cells)

CRAFT's Python scripts (`Weather_By_Python/`) will:
- Download NASA POWER data (TMAX, TMIN, SRAD) per cell
- Download CHIRPS precipitation data
- Merge both sources into final `.WTH` files at `C:\\CCAFSToolkit\\WeatherData\\Data\\`

**Note:** Do NOT load `input.csv` directly into CRAFT. It is an input for the
weather download pipeline, not a data file to be uploaded.

### Step 3: Upload Soil, Crop Mask & Management Files

In CRAFT GUI, upload the following files via Data -> Upload Data:

- **Soil mask**: `soil/soil_mask.txt`
- **Crop mask**: `crop_mask/mask.txt`
- **Cultivar data**: `management/cultivar_data.txt`
- **Planting data**: `management/planting_data.txt`
- **Fertilizer data**: `management/fertilizer_data.txt`

Copy the DSSAT soil profile to the DSSAT soil directory:
```
soil/{country_code}.SOL  -->  C:\\DSSAT48\\Soil\\{country_code}.SOL
```

### Step 4: Run Simulation

Configure simulation parameters in CRAFT GUI:
- Select region: **{region_name}**
- Select crop: **{crop_name}**
- Set simulation period: **{start_year}-{end_year}**
- Run spatial simulation

---

## File Format Reference

### Schema (5m_*.txt)
```
CELLID    SHAREPERCENT
4054256   3.06
4054255   7.96
...
```
- `CELLID`: 5-arcmin global grid cell ID (row × 4320 + col + 1)
- `SHAREPERCENT`: Percentage of cell within admin boundary

### Planting Data (15 columns)
```
CellID  PDATE  EDATE  PPOP  PPOE  PLME  PLDS  PLRS  PLRD  PLDP  PLWT  PAGE  PENV  PLPH  Percent_Share
```
- `PDATE`: Planting date (MMDD format, e.g., "0604" = June 4)
- `PPOP`: Plant population (plants/m²)
- `PLRS`: Row spacing (cm)
- `PLDP`: Planting depth (cm)

### Fertilizer Data (14 columns)
```
CellID  Level  FDATE  FMCD  FACD  FDEP  FAMN  FAMP  FAMK  FAMC  FAMO  FOCD  Name  Percent_Fraction
```
- `FDATE`: Days after planting
- `FAMN`: Nitrogen (kg/ha)
- `FAMP`: P₂O₅ (kg/ha)
- `FAMK`: K₂O (kg/ha)

### Soil Mask (3 columns)
```
CellID    SoilProfile    SharePCT
4054256   ML00001234     1
```

---

## Configuration Used

Key parameters from configuration:

| Parameter | Value |
|-----------|-------|
| **Cultivar** | {cultivar} |
| **Plant population** | {plant_pop} plants/m² |
| **Row spacing** | {row_spacing} cm |
| **Total N** | {total_n} kg/ha |
| **Planting date** | {planting_date} |
| **N split** | {n_split_ratio} (app1/app2) |

---

## Validation

This package was validated for:
- All required directories present (schema, weather, soil, crop_mask, management)
- CRAFT schema format compliance (CELLID, SHAREPERCENT columns)
- Management files sorted by CellID descending
- File checksums recorded in manifest.json

See `provenance.json` for complete data lineage.

---

## Troubleshooting

**Missing weather data**
- Ensure `weather/input.csv` was copied to `C:\\CCAFSToolkit\\Weather_By_Python\\`
- Download weather via CRAFT GUI (Data -> Weather Data -> Download from NASA)
- Ensure date range covers the full simulation period

**Soil profile not found**
- Check soil_mask.txt maps CellID to profile in .SOL file
- Verify profile names match exactly (case-sensitive)

**Zero or NaN yields**
- Verify planting date falls within growing season
- Check crop mask shows crop presence > 0

---

## Citation

```bibtex
@software{{prismpy,
  title = {{prismpy: Data-to-Model Translation for Spatial Crop Modeling}},
  year = {{2026}},
  note = {{CRAFT package generated: {generated_at}}}
}}
```

---

*Package version: 1.0 | Generator: prismpy | Platform: CRAFT*
'''


# ACEA README template
ACEA_README_TEMPLATE = '''# {project_name}

**ACEA (AquaCrop) Input Data Package**

Generated by prismpy

---

## Quick Start

```bash
# Install package to ACEA
python install.py /path/to/ACEA/data/acea

# Run simulation
cd /path/to/ACEA
python -c "from projects.{project_name}_config import project_conf; \\
           from modules.acea.acea_simulation import acea_model; \\
           model = acea_model(project_conf()); model.Run()"
```

---

## Package Overview

| Property | Value |
|----------|-------|
| **Region** | {region_name}, {country} |
| **Crop** | {crop_name} |
| **Period** | {start_year}-{end_year} |
| **Grid Cells** | {n_cells} (30-arcmin resolution) |
| **Climate Source** | {climate_source} |
| **Generated** | {generated_at} |

---

## Package Contents

```
{package_name}/
├── README.md                    # This file
├── manifest.json                # File inventory with SHA256 checksums
├── provenance.json              # Data sources and processing decisions
├── install.py                   # Installer script for ACEA
│
├── climate/
│   └── {climate_name}_{{cell_id}}.pckl   # Daily climate pickles ({n_climate_files} files)
│
├── soil/
│   ├── soil_data.csv            # Per-cell soil properties
│   └── HWSD_soil_data_on_cropland_v2.3.nc  # NetCDF for ACEA
│
├── crop_calendar/
│   ├── calendar.csv             # Planting/harvest dates
│   └── *.nc                     # NetCDF format for ACEA
│
├── crop_params/
│   ├── params.yaml              # Crop parameters
│   └── *.nc                     # NetCDF format for ACEA
│
├── harvested_areas/
│   └── {fao_code}/
│       └── spam*.tif            # SPAM harvested area rasters
│
├── gaez/
│   ├── LUT/                     # Crop suitability lookup tables
│   ├── PotentialYield/          # Potential yield rasters
│   └── F3/                      # Yield gap factor rasters
│
├── co2/
│   └── GlobalHistoricalCO2_NOAA_1980_2020.txt
│
└── config/
    ├── {project_name}_config.py # ACEA project configuration
    └── {project_name}_config.json
```

---

## Data Sources

| Data Type | Source | Description |
|-----------|--------|-------------|
| **Climate** | {climate_source} | Daily Tmax, Tmin, Precip, ET0 |
| **Soil** | {soil_source} | Sand, clay, organic carbon |
| **Harvested Area** | {spam_source} | Crop area fractions |
| **Crop Suitability** | {gaez_source} | LUT, yield potential, gap factors |
| **CO2** | NOAA | Historical atmospheric CO2 levels |

---

## Grid Cell System

ACEA uses a **30-arcmin global grid**:

- **Cell ID formula**: `row × 720 + col`
- **Row**: `(90° - latitude) × 2` (0 at North Pole)
- **Column**: `(longitude + 180°) × 2` (0 at Date Line)

**This package covers cells**: {gridcells_preview}

---

## Installing to ACEA

### Automatic Installation

```bash
# Run the install script
python install.py /path/to/ACEA/data/acea

# This copies:
# - Climate pickles to climate/
# - Soil data (merged with existing)
# - GAEZ data to gaez/
# - Harvested areas to harvested_areas/
# - Project config to projects/
```

### Manual Installation

Copy files to your ACEA installation:

```
ACEA/
├── data/
│   └── acea/
│       ├── climate/     ← climate/*.pckl
│       ├── soil/        ← soil/HWSD_*.nc (merge)
│       ├── gaez/        ← gaez/*
│       └── harvested_areas/  ← harvested_areas/*
└── projects/
    └── {project_name}_config.py  ← config/*.py
```

---

## Running ACEA Simulation

```python
import os
os.chdir('/path/to/ACEA')

from modules.acea.acea_simulation import acea_model
from projects.{project_name}_config import project_conf

# Initialize
conf = project_conf()
print(f"Simulating {{conf.project_name}} with {{len(conf.gridcells)}} cells")

# Run simulation
model = acea_model(conf)
model.Run()

# Results in ACEA/outputs/
```

### Limiting Cells for Testing

```python
conf = project_conf()
conf.gridcells = conf.gridcells[:5]  # First 5 cells only
conf.scenarios = [1]  # Rainfed only
model = acea_model(conf)
model.Run()
```

---

## Configuration Reference

### {project_name}_config.py

| Parameter | Value | Description |
|-----------|-------|-------------|
| `project_name` | {project_name} | Project identifier |
| `crop_name` | {crop_name} | Crop being simulated |
| `crop_fao` | {fao_code} | ACEA internal crop code |
| `climate_name` | {climate_name} | Climate file prefix |
| `gridcells` | [...] | List of 30-arcmin cell IDs |
| `clock_start` | {clock_start} | Simulation start |
| `clock_end` | {clock_end} | Simulation end |
| `resolution` | {resolution} | 0=30arcmin, 1=5arcmin |
| `scenarios` | {scenarios} | 1=rainfed, 2=irrigated |

---

## ACEA Crop Codes

ACEA uses internal crop codes (different from FAO):

| Crop | ACEA Code | FAO Code |
|------|-----------|----------|
| Wheat | 15 | 15 |
| Maize | 56 | 44 |
| Rice | 27 | 27 |
| Sorghum | 83 | 83 |
| Millet | 79 | 79 |
| Soybean | 236 | 236 |

This package uses **ACEA code {fao_code}** for **{crop_name}**.

---

## Troubleshooting

**"Climate file not found"**
- Verify climate files are named `{{climate_name}}_{{cell_id}}.pckl`
- Check `climate_name` in config matches file prefix

**"Missing soil data" (0 cells run)**
- ACEA's soil NetCDF may not cover your region
- The install script merges soil data - verify merge succeeded

**"No module named 'projects.xxx_config'"**
- Ensure config was copied to ACEA/projects/
- Verify Python path includes ACEA directory

---

## Validation

This package was validated for:
- All climate pickles contain valid data arrays
- Soil CSV has required columns
- GAEZ files are GeoTIFF format
- Config file is valid Python
- File checksums match manifest

See `manifest.json` and `provenance.json` for complete details.

---

## Citation

```bibtex
@software{{prismpy,
  title = {{prismpy: Data-to-Model Translation for Crop Modeling}},
  year = {{2026}},
  note = {{ACEA package generated: {generated_at}}}
}}

@software{{acea,
  title = {{ACEA: AquaCrop for Large Area Simulations}},
  author = {{FAO}},
  url = {{https://github.com/FAO-ACEA/ACEA}}
}}
```

---

*Package version: 1.0 | Generator: prismpy | Platform: ACEA*
'''


# PYTHIA README template
PYTHIA_README_TEMPLATE = '''# {project_name}

**PYTHIA/DSSAT Spatial Simulation Package**

Generated by prismpy

---

## Quick Start

```bash
# From the package directory
cd {package_dir}
pythia --all config/pythia_config.json
```

---

## Package Overview

| Property | Value |
|----------|-------|
| **Region** | {region_name}, {country} |
| **Crop** | {crop_name} |
| **Sites** | {n_sites} grid points |
| **Period** | {start_year}-{end_year} ({n_years} years) |
| **Weather Station Prefix** | {wsta_prefix} |
| **Generated** | {generated_at} |

---

## Package Contents

```
{package_dir}/
├── README.md                    # This file
├── manifest.json                # File inventory with SHA256 checksums
├── provenance.json              # Data sources and processing decisions
│
├── config/
│   └── pythia_config.json       # PYTHIA JSON configuration
│
├── shapes/
│   └── sites.shp                # Site locations ({n_sites} points)
│       └── (.shx, .dbf, .prj, .cpg)
│
├── weather/
│   └── *.WTH                    # DSSAT weather files ({n_weather_files} files)
│
├── raster/
│   ├── soil.tif                 # eGHR soil ID raster
│   ├── harvest_area.tif         # SPAM crop harvest area
│   ├── fertilizer.tif           # Fertilizer application (kg N/ha)
│   ├── planting_doy.tif         # Planting day of year
│   └── cultivar.tif             # Cultivar zone
│
├── eGHR/                        # Soil database (self-contained)
│   ├── GHR.db                   # SQLite pixel→profile mapping
│   └── *.SOL                    # DSSAT soil profiles ({n_sol_files} files)
│
└── templates/
    └── {template_name}          # DSSAT experiment template
```

---

## Data Sources

| Data Type | Source | Version | Description |
|-----------|--------|---------|-------------|
| Weather | {climate_source} | {start_year}-{end_year} | Daily SRAD, TMAX, TMIN, RAIN, TDEW, RHUM, WIND |
| Soil | eGHR (GGCMI) | v2 | DSSAT-compatible soil profiles |
| Crop Mask | SPAM | 2020 v2.0 | Harvested area distribution |
| Boundary | GADM | v4.1 | Administrative boundaries |

---

## Configuration Summary

### Crop Parameters

| Parameter | Value |
|-----------|-------|
| Crop | {crop_name} |
| Cultivar Code | {cultivar_code} |
| Cultivar Name | {cultivar_name} |
| Total GDD | {total_gdd} °C-days |
| Planting Window | {pfrst} to {plast} |

### Management Settings

| Parameter | Value |
|-----------|-------|
| Fertilizer N | {fen_tot} kg/ha |
| Plant Population | {plant_pop} plants/m² |
| Row Spacing | {row_spacing} cm |
| Irrigation | {irrigation} |

---

## Running PYTHIA Simulation

### Prerequisites

1. **DSSAT 4.8+** installed
2. **PYTHIA** Python package
3. **eGHR soil database** (included in package)

### Basic Execution

```bash
# Navigate to package directory
cd {package_dir}

# Run all simulations
pythia --all config/pythia_config.json

# Run specific site
pythia --site 1 config/pythia_config.json

# Run with verbose output
pythia --all --verbose config/pythia_config.json
```

### Output Location

Results are written to the `workDir` specified in config (default: `./`):
```
output/
├── Maize_baseline/      # Scenario 1 results
│   └── *.OUT            # DSSAT output files
└── Maize_fertilized/    # Scenario 2 results
    └── *.OUT
```

---

## SNX Template Variables

The experiment template (`{template_name}`) uses Jinja2 variables that PYTHIA fills at runtime:

### Site-Specific Variables (from shapefile/rasters)

| Variable | Source | Description |
|----------|--------|-------------|
| `{{{{ wsta }}}}` | `lookup_wth::` | Weather station code |
| `{{{{ id_soil }}}}` | `lookup_ghr::raster::` | Soil profile ID |
| `{{{{ xcrd }}}}` | shapefile | Site longitude |
| `{{{{ ycrd }}}}` | shapefile | Site latitude |

### Simulation Variables (from config)

| Variable | Source | Description |
|----------|--------|-------------|
| `{{{{ sdate }}}}` | `sdate` | Simulation start date |
| `{{{{ nyers }}}}` | `nyers` | Number of years |
| `{{{{ pfrst }}}}` | `pfrst` | First planting date |
| `{{{{ plast }}}}` | `plast` | Last planting date |
| `{{{{ ph2ol }}}}` | `ph2ol` | Soil moisture threshold (%) |
| `{{{{ ingeno }}}}` | `ingeno` | Cultivar genetic code |
| `{{{{ cname }}}}` | `cname` | Cultivar name |
| `{{{{ irrig }}}}` | `irrig` | Irrigation code (N/A/F) |

### Initial Conditions Variables

| Variable | Description |
|----------|-------------|
| `{{{{ icrt }}}}` | Initial root weight |
| `{{{{ icres }}}}` | Initial residue |
| `{{{{ icren }}}}` | Residue N concentration |
| `{{{{ ic_layers }}}}` | Soil layer initial conditions |
| `{{{{ flhst }}}}` | Flood history code |
| `{{{{ fhdur }}}}` | Flood duration |

### Fertilizer Variables

| Variable | Description |
|----------|-------------|
| `{{{{ fertilizers }}}}` | List of fertilizer applications |
| `{{{{ fert.fdap }}}}` | Days after planting |
| `{{{{ fert.famn }}}}` | Nitrogen amount (kg/ha) |

---

## Weather File Format (.WTH)

DSSAT weather file format:

```
$WEATHER DATA: Generated by prismpy

@ INSI       LAT      LONG    ELEV   TAV   AMP REFHT WNDHT
  S001  12.79   -5.62   -99  26.5  5.2   2.0   2.0

@  DATE  SRAD  TMAX  TMIN  RAIN  TDEW  RHUM  WIND
2010001  15.2  32.1  22.3   0.0  20.5  75.0   2.1
2010002  14.8  31.5  21.8   5.2  19.8  80.0   1.8
...
```

| Column | Units | Description |
|--------|-------|-------------|
| DATE | YYDDD | Year + day of year |
| SRAD | MJ/m²/day | Solar radiation |
| TMAX | °C | Maximum temperature |
| TMIN | °C | Minimum temperature |
| RAIN | mm | Precipitation |
| TDEW | °C | Dew point temperature |
| RHUM | % | Relative humidity |
| WIND | m/s | Wind speed |

---

## Soil Profile Lookup

The package uses eGHR (Enhanced Global Harmonized soils) for soil profiles:

1. **Raster** (`raster/soil.tif`): Contains pixel IDs
2. **Database** (`eGHR/GHR.db`): Maps pixel IDs → profile names
3. **Profiles** (`eGHR/*.SOL`): DSSAT soil profile files

**Lookup flow**:
```
soil.tif pixel (e.g., 5328648)
    → GHR.db lookup → "ML04002407"
    → ML.SOL file → Full soil profile
```

---

## Validation

This package includes:
- ✅ {n_weather_files} weather files with {n_years} years of data
- ✅ {n_sites} site locations in shapefile
- ✅ 5 management/soil rasters
- ✅ eGHR soil database with {n_sol_files} country profiles
- ✅ DSSAT experiment template with Jinja2 variables

See `manifest.json` for file checksums and `provenance.json` for data lineage.

---

## Troubleshooting

**"Invalid configuration file"**
- Check all paths in config use `./` prefix (relative to package)
- Verify template filename matches actual file

**"Weather file not found"**
- Weather files use sequential naming (1.WTH, 2.WTH, ...)
- Check `wsta` prefix matches expected pattern

**"Soil profile not found"**
- Verify `ghr_root` points to `./eGHR/`
- Check country .SOL file exists for your region

**"Field level not found"**
- Ensure wsta lookup prefix is not empty
- Check shapefile has uppercase `ID` field

---

## Citation

```bibtex
@software{{prismpy,
  title = {{prismpy: Data-to-Model Translation for Crop Modeling}},
  year = {{2026}},
  note = {{PYTHIA package generated: {generated_at}}}
}}

@software{{pythia,
  title = {{PYTHIA: Python Thinkpiece for Intelligent Agriculture}},
  note = {{Spatial DSSAT simulation framework}}
}}

{climate_citation}
```

---

*Package version: 1.0 | Generator: prismpy | Platform: PYTHIA/DSSAT*
'''


def get_readme_template(platform: str = "sarra_py") -> str:
    """
    Get README template for a platform.

    Args:
        platform: Target platform name

    Returns:
        Template string
    """
    templates = {
        "sarra_py": SARRA_PY_README_TEMPLATE,
        "craft": CRAFT_README_TEMPLATE,
        "acea": ACEA_README_TEMPLATE,
        "pythia": PYTHIA_README_TEMPLATE,
    }
    return templates.get(platform, SARRA_PY_README_TEMPLATE)


def _coalesce(*values: Any, default: Any = None) -> Any:
    """Return the first value that is neither ``None`` nor an empty
    string. Falls through to ``default`` when every candidate is
    empty.

    The README generator and its callers used to chain
    ``getattr(obj, name, default_str)`` and ``config.get(key,
    default_str)`` to populate the management table. Both forms
    return the actual ``None`` value when the attribute or key
    exists but its value is ``None``, which is exactly what the
    upstream wizard writes when a field is left at its platform-
    specific default. The resulting README rendered ``None`` as
    a literal string in the management rows. ``_coalesce``
    treats ``None`` and empty strings as "not set" so the
    fallback chain reaches the actual default.
    """
    for v in values:
        if v is None:
            continue
        if isinstance(v, str) and not v.strip():
            continue
        return v
    return default


def _safe_get(config: Dict[str, Any], key: str, default: Any) -> Any:
    """Return ``config[key]`` when it's a real value (non-None,
    non-empty-string); otherwise return ``default``.

    Plain ``dict.get(key, default)`` returns the actual value
    when the key is present, even if that value is ``None``.
    Upstream callers now write ``None`` to many keys when the
    wizard pins at a platform-specific config path, which lets
    the literal string ``"None"`` leak into the rendered README
    cells. ``_safe_get`` plugs that gap so every value the
    README template formats is a real fallback.
    """
    return _coalesce(config.get(key), default=default)


def _resolve_cultivar_from_disk(package_dir: Optional[Path]) -> Optional[str]:
    """Per the F-AF-v2 canonical-source contract: the on-disk
    ``management/cultivar_data.txt`` is the truth for the
    cultivar the package will run with. The README inherits
    from the file rather than from one of N possible config
    paths so the table always agrees with what DSSAT loads.

    Returns the CultivarID column from the first data row, or
    ``None`` if the file is absent or unreadable. Callers fall
    back to the config chain on ``None``.
    """
    if package_dir is None:
        return None
    cultivar_file = Path(package_dir) / "management" / "cultivar_data.txt"
    if not cultivar_file.exists():
        return None
    try:
        text = cultivar_file.read_text(encoding="utf-8")
    except (IOError, OSError):
        return None
    for line in text.splitlines()[1:]:  # skip header row
        line = line.strip()
        if not line:
            continue
        parts = line.split()
        if len(parts) >= 2:
            return parts[1]  # CellID, CultivarID, ...
    return None


def _resolve_planting_date(config: Dict[str, Any]) -> str:
    """Render a calendar date for the README management table.

    Priority chain:
    1. ``config['planting_date']`` if it's a real MMDD string
       (e.g. ``"0531"``) and not the placeholder ``"MMDD"``.
    2. Computed from ``crop.calendar.planting_doy`` +
       ``temporal.start_year``: doy=152, year=2018 →
       ``"May 31, 2018"``.
    3. Fallback ``"date not specified"`` so the table never
       renders ``None``.

    The DOY+year computation matches the in-pipeline render at
    ``CraftTranslator._generate_planting_data`` so the README
    surfaces the same date the actual planting_data.txt encodes.
    """
    raw_pdate = config.get('planting_date')
    if raw_pdate and isinstance(raw_pdate, str) and raw_pdate not in ('MMDD', 'None'):
        return raw_pdate
    doy = config.get('planting_doy')
    if doy is None:
        crop_block = config.get('crop')
        if isinstance(crop_block, dict):
            cal = crop_block.get('calendar')
            if isinstance(cal, dict):
                doy = cal.get('planting_doy')
    year = config.get('start_year')
    if year is None:
        temporal = config.get('temporal')
        if isinstance(temporal, dict):
            year = temporal.get('start_year')
    if doy is not None and year is not None:
        try:
            from datetime import date, timedelta
            d = date(int(year), 1, 1) + timedelta(days=int(doy) - 1)
            return d.strftime("%b %d, %Y")
        except (ValueError, TypeError):
            return "date not specified"
    return "date not specified"


def _resolve_management_table(
    config: Dict[str, Any],
    package_dir: Optional[Path] = None,
) -> Dict[str, Any]:
    """Return the management-table values for the CRAFT README,
    coalescing every field through a non-None fallback chain so
    the table never renders ``"None"`` for a real package.

    The on-disk ``cultivar_data.txt`` is the canonical source
    for cultivar (matches what DSSAT loads). Plant population,
    row spacing, and total nitrogen coalesce through the
    config chain to a sensible default. Planting date computes
    from doy+year when the upstream MMDD string is the
    placeholder.
    """
    cultivar = _coalesce(
        _resolve_cultivar_from_disk(package_dir),
        config.get('cultivar'),
        default='cultivar not specified',
    )
    plant_pop = _coalesce(
        config.get('plant_pop'),
        default=5.5,
    )
    row_spacing = _coalesce(
        config.get('row_spacing'),
        default=75,
    )
    total_n = _coalesce(
        config.get('total_n'),
        default=40.0,
    )
    planting_date = _resolve_planting_date(config)
    n_split_ratio = _coalesce(
        config.get('n_split_ratio'),
        default='0.25/0.75',
    )
    return {
        'cultivar': cultivar,
        'plant_pop': plant_pop,
        'row_spacing': row_spacing,
        'total_n': total_n,
        'planting_date': planting_date,
        'n_split_ratio': n_split_ratio,
    }


def _resolve_admin_names(config: Dict[str, Any]) -> str:
    """Build the ``{admin_names}`` placeholder used by the
    README dir-tree to label the schema files. The CRAFT
    translator joins level1, level2, and (for craft_level > 2)
    level3 admin names with underscores; any of those parts
    can be ``None`` when the wizard pinned a coarser admin
    level than the package's craft_level. The README rendered
    ``"Madarounfa_None"`` (level2 missing) or
    ``"Region_None_District"`` (level2 missing under a
    level3-aware schema) while the actual on-disk file dropped
    the ``None`` segment entirely.

    The fix splits the raw ``admin_names`` on the underscore
    delimiter and rebuilds it from the surviving non-empty
    parts, which matches the shape every CRAFT companion
    writer emits on disk.
    """
    raw = _coalesce(config.get('admin_names'))
    if isinstance(raw, str) and raw:
        # Drop any segment that's literally ``None`` or empty.
        # Handles the trailing case (``Madarounfa_None``) and
        # the interior case (``Region_None_District``) the
        # level3-aware schema can produce when the wizard
        # only resolved a level1 and the schema was upgraded
        # to level3.
        parts = [
            p for p in raw.split('_')
            if p and p.lower() != 'none'
        ]
        if parts:
            return '_'.join(parts)
    # Reconstruct from parts if the raw form was empty or
    # collapsed to nothing after filtering.
    level1 = _coalesce(config.get('admin_level1_name'))
    level2 = _coalesce(config.get('admin_level2_name'))
    level3 = _coalesce(config.get('admin_level3_name'))
    region_name = _coalesce(
        config.get('region_name'),
        config.get('region', {}).get('name') if isinstance(config.get('region'), dict) else None,
    )
    parts = [p for p in (level1, level2, level3) if p]
    if parts:
        return '_'.join(parts)
    if region_name:
        return region_name
    return 'admin_names_unavailable'


def generate_readme(
    output_path: Union[str, Path],
    config: Dict[str, Any],
    platform: str = "sarra_py"
) -> Path:
    """
    Generate README from template.

    Args:
        output_path: Path to output README
        config: Configuration dictionary with package metadata
        platform: Target platform name

    Returns:
        Path to generated README
    """
    template = get_readme_template(platform)

    # Prepare substitution values
    region_name = config.get('region_name', config.get('region', {}).get('name', 'Unknown'))
    package_name = config.get('package_name', f"{region_name.lower()}_package")

    # Resolve gadm_level for the boundary cell. Translators emit
    # ``None`` for non-GADM resolved sources via the manifest's
    # resolved-source discriminator; rendering that None as
    # ``Admin Level None`` would leak the runtime sentinel into
    # the user-visible README. Map it to ``Admin Level: N/A`` so
    # the boundary row stays readable for manual / shapefile /
    # GADM-failed-fallback packages.
    raw_gadm_level = config.get(
        'gadm_level',
        config.get('region', {}).get('gadm_level'),
    )
    if raw_gadm_level is None:
        admin_level_label = "Admin Level: N/A"
    else:
        admin_level_label = f"Admin Level {raw_gadm_level}"

    # Common values for all platforms — every entry passes
    # through ``_safe_get`` (or its inline equivalent) so a
    # present-but-None key cannot leak the literal "None" into
    # the rendered template.
    region_block = config.get('region') if isinstance(config.get('region'), dict) else {}
    crop_block = config.get('crop') if isinstance(config.get('crop'), dict) else {}
    temporal_block = config.get('temporal') if isinstance(config.get('temporal'), dict) else {}
    data_sources = config.get('data_sources') if isinstance(config.get('data_sources'), dict) else {}
    values = {
        'project_name': _safe_get(config, 'project_name', package_name),
        'package_name': package_name,
        'region_name': region_name,
        'country': _coalesce(
            config.get('country'),
            region_block.get('country'),
            default='Unknown',
        ),
        'crop_name': _coalesce(
            config.get('crop_name'),
            crop_block.get('name'),
            default='Unknown',
        ),
        'start_year': _coalesce(
            config.get('start_year'),
            temporal_block.get('start_year'),
            default=2017,
        ),
        'end_year': _coalesce(
            config.get('end_year'),
            temporal_block.get('end_year'),
            default=2017,
        ),
        'generated_at': datetime.now().strftime('%Y-%m-%d %H:%M:%S'),
        'gadm_level': raw_gadm_level if raw_gadm_level is not None else 'N/A',
        'admin_level_label': admin_level_label,
        'boundary_source': _coalesce(
            data_sources.get('boundaries'),
            default='GADM v4.1',
        ),
        'rainfall_source': _coalesce(
            data_sources.get('rainfall'),
            default='TAMSAT v3.1',
        ),
        'temperature_source': _coalesce(
            data_sources.get('temperature'),
            default='AgERA5',
        ),
        'soil_source': _coalesce(
            data_sources.get('soil'),
            default='iSDA',
        ),
    }

    # CRAFT-specific values
    if platform == "craft":
        # F-AF-v2 + F-AN absorption — derive the package directory
        # from the README path so the management-table resolvers
        # can read ``management/cultivar_data.txt`` (the canonical
        # source) and the dir-tree resolver can emit a filename
        # that matches the on-disk schema files. The README path
        # is always at the package-root, so its parent is the
        # package directory the resolvers walk.
        package_dir = Path(output_path).parent
        management_values = _resolve_management_table(config, package_dir)
        admin_names = _resolve_admin_names(config)

        values.update({
            # Package metadata
            'n_cells': _safe_get(config, 'n_cells', 0),
            'n_soil_profiles': _safe_get(config, 'n_soil_profiles', 0),
            'craft_level': _coalesce(
                config.get('craft_level'),
                config.get('schema_level'),
                default=2,
            ),
            'admin_names': admin_names,
            'country_code': _safe_get(config, 'country_code', 'ML'),

            # Data sources with descriptions
            # V2-19b-fix Finding 7: default to "source unavailable" not
            # "HWSD v2.0" — the caller must set soil_source explicitly
            # from the actual SoilProfile.source field.
            'soil_source': _safe_get(config, 'soil_source', 'source unavailable'),
            'soil_description': _safe_get(config, 'soil_description', 'Soil source not specified'),
            'crop_mask_source': _safe_get(config, 'crop_mask_source', 'SPAM 2020'),
            'crop_mask_description': _safe_get(config, 'crop_mask_description', 'Harvested area fractions'),
            'boundary_source': _safe_get(config, 'boundary_source', 'GADM v4.1'),
            'boundary_description': _safe_get(config, 'boundary_description', 'Administrative boundaries'),

            # Management parameters — F-AF-v2: every field passes
            # through ``_resolve_management_table`` so a None
            # value upstream (wizard pinned at platform_config
            # while management.default_cultivar stayed None, etc.)
            # never reaches the rendered string.
            'cultivar': management_values['cultivar'],
            'plant_pop': management_values['plant_pop'],
            'row_spacing': management_values['row_spacing'],
            'total_n': management_values['total_n'],
            'planting_date': management_values['planting_date'],
            'n_split_ratio': management_values['n_split_ratio'],
        })

    # ACEA-specific values — H6 absorption: every value coalesces
    # through a non-None chain so the rendered table never carries
    # the literal "None" cell.
    if platform == "acea":
        gridcells = _coalesce(config.get('gridcells'), default=[])
        gridcells_preview = str(gridcells[:5]) + '...' if len(gridcells) > 5 else str(gridcells)
        start_year_safe = _safe_get(config, 'start_year', 2016)
        end_year_safe = _safe_get(config, 'end_year', 2020)

        values.update({
            # Package metadata
            'n_cells': _coalesce(config.get('n_cells'), default=len(gridcells)),
            'n_climate_files': _safe_get(config, 'n_climate_files', 0),
            'fao_code': _safe_get(config, 'fao_code', 56),

            # Climate
            'climate_name': _safe_get(
                config, 'climate_name',
                f"{region_name.lower()}_nasapower",
            ),
            'climate_source': _safe_get(config, 'climate_source', 'NASA POWER'),
            'climate_citation': _safe_get(
                config, 'climate_citation',
                '@misc{nasa_power,\n  title = {NASA POWER: Prediction Of '
                'Worldwide Energy Resources},\n  url = {https://power.larc.'
                'nasa.gov/}\n}',
            ),

            # Data sources
            # V2-19b-fix Finding 7: same fix as CRAFT — honest default.
            'soil_source': _safe_get(config, 'soil_source', 'source unavailable'),
            'spam_source': _safe_get(config, 'spam_source', 'Dummy (placeholder)'),
            'gaez_source': _safe_get(config, 'gaez_source', 'FAO GAEZ v4'),

            # Grid cells
            'gridcells_preview': gridcells_preview,

            # Config parameters
            'clock_start': _safe_get(
                config, 'clock_start', f"{start_year_safe}/01/01",
            ),
            'clock_end': _safe_get(
                config, 'clock_end', f"{end_year_safe}/12/31",
            ),
            'resolution': _safe_get(config, 'resolution', 1),
            'scenarios': _coalesce(config.get('scenarios'), default=[1]),
        })

    # PYTHIA-specific values — H6 absorption: every value
    # coalesces through ``_safe_get`` so present-but-None
    # config keys can't render the literal "None".
    if platform == "pythia":
        end_year_p = _safe_get(config, 'end_year', 2019)
        start_year_p = _safe_get(config, 'start_year', 2010)
        try:
            default_n_years = int(end_year_p) - int(start_year_p) + 1
        except (TypeError, ValueError):
            default_n_years = 10
        values.update({
            # Package metadata
            'package_dir': _safe_get(config, 'package_dir', 'pythia'),
            'n_sites': _safe_get(config, 'n_sites', 0),
            'n_weather_files': _safe_get(config, 'n_weather_files', 0),
            'n_years': _safe_get(config, 'n_years', default_n_years),
            'n_sol_files': _safe_get(config, 'n_sol_files', 0),
            'wsta_prefix': _safe_get(config, 'wsta_prefix', 'MLKO'),
            'template_name': _safe_get(config, 'template_name', 'KOMZ8001.SNX'),

            # Crop parameters
            'cultivar_code': _safe_get(config, 'cultivar_code', '990002'),
            'cultivar_name': _safe_get(config, 'cultivar_name', 'MEDIUM_SEASON'),
            'total_gdd': _safe_get(config, 'total_gdd', 'N/A'),
            'pfrst': _safe_get(config, 'pfrst', 'N/A'),
            'plast': _safe_get(config, 'plast', 'N/A'),

            # Management settings
            'fen_tot': _safe_get(config, 'fen_tot', 60),
            'plant_pop': _safe_get(config, 'plant_pop', 5.0),
            'row_spacing': _safe_get(config, 'row_spacing', 70),
            'irrigation': _safe_get(config, 'irrigation', 'Rainfed'),
            'climate_source': _safe_get(config, 'climate_source', 'NASA POWER'),
            'climate_citation': _safe_get(
                config, 'climate_citation',
                '@misc{nasa_power,\n  title = {NASA POWER: Prediction Of '
                'Worldwide Energy Resources},\n  url = {https://power.larc.'
                'nasa.gov/}\n}',
            ),
        })

    # Format template
    readme_content = template.format(**values)

    # Write output
    output_path = Path(output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)

    with open(output_path, 'w', encoding='utf-8') as f:
        f.write(readme_content)

    return output_path
