"""The soil declaration read back from a package's own soil files: the record grammar, the
binding, each engine's inspector, the generic-soil fields consumed from CRAFT's record, and the
pedotransfer mark that survives profile dedup."""
from __future__ import annotations

import numpy as np
import pytest

from prismpy.models.soil import SoilLayer, SoilProfile
from prismpy.models.spatial import GridCell, SpatialGrid
from prismpy.packaging import soil_declaration as sd
from prismpy.translators._shared.eghr_substrate import assign_cell_to_profile_id

NO_DEFAULT = dict(default_cells=0, default_cause="-", default_fraction="0.0000", default_warning=0,
                  default_profile="-", default_depth_cm="-", default_paw_mm="-")


def _record(**fields):
    values = dict(source="profiles", profile_sources="hwsd:2", no_profile_cells=0, override_cells=0,
                  ptf_layers=0, profiles=1, layers=5, organic_layers=0, andic_layers=0,
                  chem_defaulted="bulk_density:0,organic_carbon:0,ph:0",
                  chem_default_values="bulk_density:1.40,organic_carbon:0.50,ph:6.5",
                  cells_with_flagged_layers=0, cells_with_defaulted_chemistry=0, cells=2, **NO_DEFAULT)
    values.update(fields)
    return sd.format_record([(key, values[key]) for key in sd.SOL_RECORD_KEYS])


def _sol(path, record, profiles):
    """A .SOL laid out as the writer writes it: record line, then each profile header."""
    lines = ["*SOILS: R - Generated by prismpy (test)"] + ([record] if record else []) + [""]
    for name, token, depth in profiles:
        lines.append(f"*{name:<10}  {token:<11} {'SL':<5} {depth:>5d} test")
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\r\n".join(lines) + "\r\n")


def _craft(tmp_path, profiles, rows, **record):
    soil = tmp_path / "soil"
    _sol(soil / "ML.SOL", _record(**record), profiles)
    (soil / "soil_mask.txt").write_text("CellID\tSoilProfile\tSharePCT\n" +
                                        "".join(f"{i}\t{p}\t1\n" for i, p in enumerate(rows)))
    (soil / sd.DETAIL_FILE).write_text("{}\n")
    sd.write_binding(tmp_path, "soil", [soil / "ML.SOL", soil / "soil_mask.txt", soil / sd.DETAIL_FILE])
    return tmp_path


HWSD2 = [("ML00001469", "hwsd", 100), ("ML00001470", "hwsd", 60)]


def test_the_record_grammar_round_trips_and_refuses_malformed_text():
    line = sd.format_record([("source", "profiles"), ("profile_sources", sd.format_counts([("hwsd", 3)]))])
    assert line == "! prismpy soil record: source=profiles profile_sources=hwsd:3"
    assert sd.parse_record(line) == {"source": "profiles", "profile_sources": "hwsd:3"}
    assert sd.parse_counts("-") == {} and sd.format_counts([]) == "-"
    with pytest.raises(ValueError):
        sd.format_record([("source", "two words")])
    for bad in ("! prismpy soil record: a=1 a=2", "! prismpy soil record: novalue", "! other: a=1"):
        with pytest.raises(sd.SoilDeclarationError):
            sd.parse_record(bad)
    with pytest.raises(sd.SoilDeclarationError):
        sd.SoilStamp("hwsd")
    with pytest.raises(sd.SoilDeclarationError):
        sd.profile_source_token("HWSD v2")


def test_the_binding_fails_on_any_change_to_the_bound_set(tmp_path):
    pkg = _craft(tmp_path, HWSD2, ["ML00001469", "ML00001470"])
    assert sd.declared_soil(pkg, "craft").source_id == "profiles"
    mask = pkg / "soil/soil_mask.txt"
    original = mask.read_bytes()
    mask.write_bytes(original.replace(b"ML00001470", b"ML00001469"))   # one row re-pointed
    with pytest.raises(sd.SoilDeclarationError, match="changed after it was bound"):
        sd.declared_soil(pkg, "craft")
    mask.write_bytes(original)
    (pkg / "soil" / sd.BINDING_FILE).unlink()
    with pytest.raises(sd.SoilDeclarationError, match="missing"):
        sd.declared_soil(pkg, "craft")
    sd.write_binding(pkg, "soil", [pkg / "soil/ML.SOL", mask])        # the detail file left out
    with pytest.raises(sd.SoilDeclarationError, match="binds"):
        sd.declared_soil(pkg, "craft")


def test_craft_counts_each_source_through_the_mask(tmp_path):
    rows = ["ML00001469", "ML00001469", "ML00001470"]
    decl = sd.declared_soil(_craft(tmp_path / "a", HWSD2, rows, profile_sources="hwsd:3", cells=3), "craft")
    assert decl.label.startswith(sd.SOURCE_DESCRIPTIONS["hwsd"] + ", one profile per grid cell")
    assert decl.record["profile_sources"] == {"hwsd": 3}
    assert decl.inputs_used()["record"]["hydraulics"]["reference"].startswith("Saxton KE, Rawls WJ (2006)")
    # a record that disagrees with the mask, even with a fresh binding
    with pytest.raises(sd.SoilDeclarationError, match="cells per source"):
        sd.declared_soil(_craft(tmp_path / "b", HWSD2, rows, profile_sources="hwsd:2", cells=3), "craft")
    with pytest.raises(sd.SoilDeclarationError, match="unknown source token"):
        sd.declared_soil(_craft(tmp_path / "c", [("ML00001469", "HWSD", 100)], ["ML00001469"],
                                profile_sources="hwsd:1", cells=1), "craft")


def _generic(tmp_path, k, n, default="ML00000000", token="default", depth=100, **record):
    profiles = [("ML00001469", "hwsd", 100), (default, token, depth)]
    rows = ["ML00001469"] * (n - k) + [default] * k
    fields = dict(profile_sources=sd.format_counts([(t, c) for t, c in (("hwsd", n - k), (token, k)) if c]),
                  cells=n, default_cells=k, default_cause=f"no_hwsd_soil_at_cell_centre:{k}",
                  default_fraction=f"{k / n:.4f}", default_warning=int(20 * k > n), default_profile=default,
                  default_depth_cm="0-100", default_paw_mm=158)
    fields.update(record)
    return sd.declared_soil(_craft(tmp_path, profiles, rows, **fields), "craft")


def test_generic_soil_fields_are_consumed_from_the_record_and_checked_for_consistency(tmp_path):
    # the placeholder package: its rows name the placeholder profile, none name the default
    decl = _generic(tmp_path / "i", 2, 2, default="ML90000001", token="placeholder",
                    default_cause="retrieve_stage_placeholder:2")
    assert decl.label.startswith("WARNING: 2 of 2 candidate grid cells run on a generic placeholder soil "
                                 "profile (0-100 cm, about 158 mm plant-available water), because the soil "
                                 "data for this package could not be retrieved when it was built.")
    assert "cell centre" not in decl.label
    # the record's depth and water, not the written profile's
    decl = _generic(tmp_path / "vi", 1, 2, default_depth_cm="0-80", default_paw_mm=126)
    assert "(0-80 cm, about 126 mm plant-available water)" in decl.label
    # the exact predicate, never the 4-dp fraction
    assert _generic(tmp_path / "iii1", 1001, 20001, default_fraction="0.0500").label.startswith("WARNING: ")
    assert "WARNING" not in _generic(tmp_path / "iii0", 1000, 20000).label
    with pytest.raises(sd.SoilDeclarationError, match="default_warning"):
        _generic(tmp_path / "iii2", 1000, 20000, default_warning=1)
    assert _generic(tmp_path / "vii", 2, 20, default_fraction="0.1234").label.startswith("WARNING: ")
    # the rows naming the default profile must be the declared count
    with pytest.raises(sd.SoilDeclarationError, match="mask rows name"):
        _generic(tmp_path / "v", 1, 3, default_cells=2, default_cause="no_hwsd_soil_at_cell_centre:2",
                 default_warning=1)
    with pytest.raises(sd.SoilDeclarationError, match="generic soil is used"):
        _generic(tmp_path / "zero", 1, 20, default_cells=0, default_cause="-", default_warning=0,
                 default_profile="-", default_depth_cm="-", default_paw_mm="-")


def _pythia(tmp_path, record, source=None, db=True):
    ghr = tmp_path / "eGHR"
    _sol(ghr / "ML.SOL", record, [("ML00000001", "isda_s3", 50)])
    files = [ghr / "ML.SOL"]
    if db:
        (ghr / "GHR.db").write_bytes(b"db")
        (tmp_path / "raster").mkdir()
        (tmp_path / "raster/soil.tif").write_bytes(b"tif")
        files += [ghr / "GHR.db", tmp_path / "raster/soil.tif"]
    if source is None:
        (ghr / sd.DETAIL_FILE).write_text("{}\n")
        files.append(ghr / sd.DETAIL_FILE)
    sd.write_binding(tmp_path, "eGHR", files, source=source)
    return tmp_path


def test_pythia_canonical_legacy_and_their_mixtures(tmp_path):
    decl = sd.declared_soil(_pythia(tmp_path / "c", _record(profile_sources="isda_s3:3", cells=4,
                                                            no_profile_cells=1, ptf_layers=2)), "pythia")
    assert decl.label.startswith(sd.SOURCE_DESCRIPTIONS["isda_s3"] + ", one profile per grid cell, stored in "
                                 "the eGHR file format")
    assert "1 of 4 grid cells have no soil profile in the package" in decl.label
    assert "for 2 of 5 layers" in decl.label and "1 of 1 profiles are shallower than 100 cm (depth 50–50 cm)" in decl.label
    assert sd.declared_soil(_pythia(tmp_path / "n", _record(source="none", profile_sources="-", profiles=0,
                                                            layers=0, cells=3, no_profile_cells=3)),
                            "pythia").label == sd.NO_PROFILE
    legacy = sd.declared_soil(_pythia(tmp_path / "l", None, source=sd.EGHR_DATABASE), "pythia")
    assert legacy.source_id == "eghr_database" and legacy.label == sd.BASE[("pythia", "eghr_database")]
    with pytest.raises(sd.SoilDeclarationError, match="database-copied"):
        sd.declared_soil(_pythia(tmp_path / "m", _record(), source=sd.EGHR_DATABASE), "pythia")
    with pytest.raises(sd.SoilDeclarationError, match="neither"):
        sd.declared_soil(_pythia(tmp_path / "u", None), "pythia")


def _acea_netcdf(path, fill=-9999.0, record="source=hwsd_upper_layer_texture cells=3 hwsd=1 default=1 masked=1"):
    import netCDF4
    path.parent.mkdir(parents=True, exist_ok=True)
    with netCDF4.Dataset(path, "w") as ds:
        ds.createDimension("lat", 2)
        ds.createDimension("lon", 2)
        for name in ("sand", "clay"):
            var = ds.createVariable(name, "f4", ("lat", "lon"), fill_value=fill)
            var[:] = np.array([[40.0, 30.0], [20.0, 10.0]], dtype="f4")
        if record:
            ds.setncattr(sd.ACEA_RECORD_ATTR, f"{sd.RECORD_PREFIX} {record}")


def test_acea_binds_the_whole_netcdf(tmp_path):
    assert sd.declared_soil(tmp_path / "none", "acea").source_id == "engine_installed"
    nc = tmp_path / sd.ACEA_SOIL_FILE
    _acea_netcdf(nc)
    sd.write_binding(tmp_path, "soil", [nc])
    decl = sd.declared_soil(tmp_path, "acea")
    assert decl.label == (sd.BASE[("acea", "hwsd_upper_layer_texture")] + "; 1 of 3 cells use a generic default "
                          "soil (sand 40%, clay 25%); 1 of 3 cells have no soil value and are skipped by the engine")
    _acea_netcdf(nc, fill=-8888.0)          # the same sand/clay values, another fill value
    with pytest.raises(sd.SoilDeclarationError, match="changed after it was bound"):
        sd.declared_soil(tmp_path, "acea")
    _acea_netcdf(nc, record=None)
    sd.write_binding(tmp_path, "soil", [nc])
    with pytest.raises(sd.SoilDeclarationError, match="carries no"):
        sd.declared_soil(tmp_path, "acea")
    (tmp_path / "soil" / sd.BINDING_FILE).unlink()
    with pytest.raises(sd.SoilDeclarationError, match="missing"):
        sd.declared_soil(tmp_path, "acea")


def test_sarra_declares_the_engine_bundled_soil(tmp_path):
    decl = sd.declared_soil(tmp_path, "sarra_py")
    assert decl.source_id == "engine_bundled_africa" and "(ac769ea) uses none of its values" in decl.label


def test_label_suffixes_name_their_numbers(tmp_path):
    decl = sd.declared_soil(_craft(tmp_path, HWSD2, ["ML00001469", "ML00001470"], ptf_layers=3,
                                   organic_layers=1, andic_layers=2, cells_with_flagged_layers=2,
                                   chem_defaulted="bulk_density:2,organic_carbon:0,ph:1"), "craft")
    assert decl.label == (
        sd.SOURCE_DESCRIPTIONS["hwsd"] + ", one profile per grid cell; water limits estimated with a pedotransfer "
        "function (Saxton & Rawls 2006, simplified) for 3 of 5 layers; 1 of 2 profiles are shallower than 100 cm "
        "(depth 60–60 cm); chemistry defaults used (bulk density 1.40 g/cm³ ×2, pH 6.5 ×1); 1 organic and 2 "
        "andic layers (of 5 layers in 1 profiles; 2 cells), outside the pedotransfer function's calibration range")
    assert decl.record["hydraulics"] == {**sd.HYDRAULICS, "estimated_layers": 3, "layers": 5}


def _profile(pid, **hydraulics):
    return SoilProfile(profile_id=pid, lat=12.0, lon=-5.0, source="isda",
                       layers=[SoilLayer(depth_top=0.0, depth_bottom=0.2, sand=50.0, clay=20.0, **hydraulics)])


def test_the_pedotransfer_mark_is_provenance_only_and_survives_dedup():
    layer = SoilLayer(depth_top=0.0, depth_bottom=0.2, sand=50.0, clay=20.0)
    plain = SoilLayer(depth_top=0.0, depth_bottom=0.2, sand=50.0, clay=20.0)
    assert not layer.hydraulics_estimated
    layer.estimate_hydraulic_properties()
    assert layer.hydraulics_estimated and "hydraulics_estimated" not in layer.to_dict()
    plain.estimate_hydraulic_properties()
    plain.hydraulics_estimated = False
    assert plain == layer                         # the mark is outside equality
    supplied = {k: getattr(layer, k) for k in ("wilting_point", "field_capacity", "saturated_wc")}
    grid = SpatialGrid(resolution="5arcmin", cells=[GridCell(cell_id=i, lat=12.0, lon=-5.0 + i / 12, row=0, col=i)
                                                     for i in (1, 2)])
    # the lower cell id supplies the same water limits the function gives; the higher one lacks them
    _, profiles = assign_cell_to_profile_id(grid, {1: _profile("a", **supplied), 2: _profile("b")})
    assert len(profiles) == 1 and profiles[1].layers[0].hydraulics_estimated
    assert profiles[1].profile_id == "a"
