"""Dynamic-CO₂ SNX wiring in the prismpy-generated package SNX (UC2 Bar-1).

The Bar-1 smoke found that the pythia adapter renders the PACKAGE's SNX
(generated by prismpy ``_build_snx_content``), NOT prism-runner's reference
``_templates/``. The package SNX previously HARDCODED ``@E ECO2 = A   0`` +
``*TREATMENTS ME = 0``, so the scenario CO₂ that the adapter injects into the
render ctx (``co2_ppm`` / ``eco2_override_active``) was never consumed → DSSAT
ran the default CO₂ series → identical yields at 400 vs 600 ppm (empirically
observed). These pins lock the fix: the generated SNX now carries the SAME
conditional jinja as the prism-runner adapter contract (builder-3's edad9be),
so CO₂ flows end-to-end. Backward-compat: with no scenario CO₂ the ``else``
branches render ``A   0`` / ``0`` — byte-identical to the pre-fix hardcode, so
legacy non-UC2 packages see zero yield drift.
"""

from __future__ import annotations

from prismpy.config.schema import (
    BoundaryConfig,
    BoundarySource,
    CropCalendarConfig,
    CropConfig,
    ManualBoundsConfig,
    OutputConfig,
    Platform,
    ProjectConfig,
    ProjectInfo,
    RegionConfig,
    TemporalConfig,
)
from prismpy.translators.pythia.translator import PythiaTranslator

# The EXACT jinja the prism-runner adapter renders (builder-3 edad9be,
# pythia.py:1800-1801 sets ctx["co2_ppm"] (int) + ctx["eco2_override_active"]
# (bool)). The generated package SNX MUST carry these verbatim or CO₂ cannot
# cross the repo boundary.
_ECO2_JINJA = (
    "{% if eco2_override_active|default(false) %}"
    "R {{ co2_ppm }}{% else %}A   0{% endif %}"
)
_ME_JINJA = "{% if eco2_override_active|default(false) %}1{% else %}0{% endif %}"


def _snx(crop: str = "Cowpea") -> str:
    cfg = ProjectConfig(
        project=ProjectInfo(name="snx_co2_pin"),
        region=RegionConfig(
            name="Kano",
            country="Nigeria",
            country_iso3="NGA",
            boundary=BoundaryConfig(
                source=BoundarySource.MANUAL,
                manual_bounds=ManualBoundsConfig(
                    minx=5.75, miny=11.25, maxx=10.25, maxy=12.75
                ),
            ),
        ),
        crop=CropConfig(
            name=crop,
            name_short=crop[:3].lower(),
            calendar=CropCalendarConfig(planting_doy=185, maturity_doy=280),
        ),
        temporal=TemporalConfig(start_year=2015, end_year=2015, spinup_years=0),
        targets=[Platform.PYTHIA],
        output=OutputConfig(base_dir="/tmp", structure="by_platform"),
    )
    t = PythiaTranslator(config=cfg)
    return t._build_snx_content(
        exp_id="KACP8001",
        region_name="Kano",
        country="Nigeria",
        crop_name=crop,
        cultivar=t._map_generic_to_cultivar(),
        fertilizer=t._map_generic_to_fertilizer(),
        config=t._map_generic_to_pythia_config(),
        ppop=6.25,
        row_spacing=70.0,
    )


def test_generated_snx_carries_eco2_and_me_co2_jinja():
    """Red→green vs the pre-fix hardcode: the generated package SNX carries the
    @E ECO2 + *TREATMENTS ME conditional jinja (so co2_ppm is consumed)."""
    snx = _snx()
    assert _ECO2_JINJA in snx, "@E ECO2 CO₂ jinja missing — co2_ppm never consumed"
    assert _ME_JINJA in snx, "*TREATMENTS ME CO₂ jinja missing"


def test_generated_snx_has_no_hardcoded_all_default_eco2_row():
    """The pre-fix @E row hardcoded all 8 mod-fields to ``A   0`` (ECO2
    included) — that MUST be gone, else the override can never fire."""
    snx = _snx()
    assert (
        "A   0 A   0 A   0 A   0 A   0 A   0 A   0 A   0 ENV modify" not in snx
    ), "stale all-default @E row still present — ECO2 hardcoded to A 0"


def test_eco2_inactive_branch_is_byte_identical_backward_compat():
    """Non-UC2 (no scenario CO₂ → ``eco2_override_active`` falsy): the jinja
    ``else`` branches render ``A   0`` (@E) and ``0`` (ME) — byte-identical to
    the pre-fix hardcode, so legacy packages see no yield drift."""
    snx = _snx()
    assert "{% else %}A   0{% endif %}" in snx, "@E ECO2 inactive != 'A   0'"
    assert "{% else %}0{% endif %}" in snx, "ME inactive != '0'"


def test_snx_co2_jinja_uses_the_adapter_ctx_key_contract():
    """The jinja MUST use the adapter's literal ctx key names, and
    ``|default(false)`` is load-bearing (an absent flag must render the inactive
    default, not raise under StrictUndefined)."""
    snx = _snx()
    assert "eco2_override_active|default(false)" in snx
    assert "{{ co2_ppm }}" in snx


def test_co2_wiring_is_crop_agnostic():
    """cowpea (C3) + sorghum (C4) are UC2's crops; both must carry the wiring."""
    for crop in ("Cowpea", "Sorghum"):
        snx = _snx(crop)
        assert _ECO2_JINJA in snx and _ME_JINJA in snx, f"{crop}: CO₂ jinja missing"
